# Generated by scripts/oss/project_local_engine.py — DO NOT EDIT.
# Regenerate rather than patch; hand edits are rejected by the drift gate.
# SPDX-License-Identifier: Apache-2.0

"""Read a legacy, OpenDocument or ebook file by way of a modern sibling.

Ten formats have no native extractor here: `.doc`, `.odt`, `.rtf`, `.xls`,
`.ods`, `.ppt`, `.odp`, `.epub`, `.mobi` and `.azw3`. Rather than a second
parser for each, this converts once into the Office Open XML sibling the engine
already reads well and then runs that sibling's extractor unchanged. One hop,
and every one of them inherits headings, tables and embedded images for free.

Which program performs the hop is a static fact about the format and comes from
the registry, not from a decision here: an office suite cannot open an EPUB, and
an ebook tool has no business converting a spreadsheet.

The conversion runs in a private temporary directory, one per call. Two
conversions of files with the same name would otherwise land on the same output
path, and an empty private directory takes any stray sibling output away with
it when it goes.

Needs LibreOffice or Calibre installed. Neither can be installed from PyPI, so
neither is an optional dependency — `convilyn.local.capabilities()` reports
which of them this machine has.
"""

from __future__ import annotations

import logging
from dataclasses import replace
from pathlib import Path
from tempfile import TemporaryDirectory

from convilyn.local._engine.formats import DocumentFormat
from convilyn.local._engine.markdown.model import MarkdownDoc
from convilyn.local._engine.markdown.registry import (
    BridgeRoute,
    bridge_for,
    extractor_for,
)
from convilyn.local._run import run_calibre, run_libreoffice

logger = logging.getLogger(__name__)

_TIMEOUT_SECONDS = 300


def _produce_sibling(path: Path, route: BridgeRoute, workdir: str) -> Path:
    if route.engine == "calibre":
        out = Path(workdir) / f"sibling.{route.bridge.value}"
        returncode, _stdout, stderr = run_calibre(str(path), str(out), timeout=_TIMEOUT_SECONDS)
        if returncode != 0:
            raise RuntimeError(f"Calibre -> {route.bridge.value} failed: {stderr}")
        if not out.exists():
            raise RuntimeError(f"Calibre reported success but wrote no {out.name}: {stderr}")
        return out

    returncode, _stdout, stderr = run_libreoffice(
        input_path=str(path),
        output_dir=workdir,
        target_format=route.bridge.value,
        timeout=_TIMEOUT_SECONDS,
    )
    if returncode != 0:
        raise RuntimeError(f"LibreOffice -> {route.bridge.value} failed: {stderr}")

    produced = sorted(Path(workdir).glob(f"*.{route.bridge.value}"))
    if not produced:
        raise RuntimeError(
            f"LibreOffice reported success but wrote no .{route.bridge.value}: {stderr}"
        )
    if len(produced) > 1:
        logger.warning(
            "bridge saw %d .%s outputs, extracting %s",
            len(produced),
            route.bridge.value,
            produced[0].name,
        )
    return produced[0]


def extract_via_bridge(path: Path, source: DocumentFormat) -> MarkdownDoc:
    """Convert a file to its modern sibling, then extract that.

    The path must still carry the original extension: both programs choose their
    import filter from the file name rather than from the bytes.

    The returned document reports the **original** source format, not the sibling's.
    The sibling is an implementation detail of reading, and a caller who saw `docx`
    for a file they gave as `.odt` would have no way to tell the two apart. It also
    carries a warning saying which sibling was used, so nothing about the route is
    hidden.

    Raises:
        ValueError: the format has no sibling, so it should not have been routed
            here at all.
        RuntimeError: the program failed, or reported success and wrote nothing.
        ToolNotInstalledError: the program is not installed on this machine.
        subprocess.TimeoutExpired: the conversion exceeded its time limit.
    """
    route = bridge_for(source)
    if route is None:
        raise ValueError(f"{source.value} has no sibling format; it cannot be bridged")

    extract = extractor_for(route.bridge)
    if extract is None:
        raise ValueError(f"sibling {route.bridge.value} of {source.value} has no native extractor")

    with TemporaryDirectory(prefix="bridge-") as workdir:
        sibling_path = _produce_sibling(path, route, workdir)

        doc = extract(sibling_path)

    return replace(
        doc,
        source_format=source.value,
        warnings=doc.warnings + (f"bridged: read via {route.bridge.value}",),
    )
