# Generated by scripts/oss/project_local_engine.py — DO NOT EDIT.
# Regenerate rather than patch; hand edits are rejected by the drift gate.
# SPDX-License-Identifier: Apache-2.0

"""Delimited text to ``MarkdownDoc``, as a single table.

The delimiter is sniffed from the start of the file rather than assumed to be a
comma, so tab- and semicolon-separated exports read correctly without the caller
having to say which they have.

Needs no optional dependency — this extractor works on a bare install.
"""

from __future__ import annotations

import csv
from pathlib import Path

from convilyn.local._engine.markdown.model import Block, MarkdownDoc
from convilyn.local._engine.markdown.text import read_text_file

MAX_ROWS = 5_000

_SNIFF_BYTES = 8_192


def _dialect(sample: str) -> type[csv.Dialect] | csv.Dialect:
    try:
        return csv.Sniffer().sniff(sample, delimiters=",;\t|")
    except csv.Error:
        return csv.excel


def extract(path: Path) -> MarkdownDoc:
    """Read a delimited-text file into one table block.

    The first row becomes the table header, matching what a reader expects of a
    spreadsheet export. Very large files are truncated at a row cap and the returned
    document says so in its warnings rather than silently losing the tail.
    """
    raw = read_text_file(path)
    if not raw.strip():
        return MarkdownDoc(source_format="csv", warnings=("empty CSV",))

    reader = csv.reader(raw.splitlines(), dialect=_dialect(raw[:_SNIFF_BYTES]))

    rows: list[tuple[str, ...]] = []
    truncated = False
    for row in reader:
        if len(rows) >= MAX_ROWS:
            truncated = True
            break
        rows.append(tuple(cell.strip() for cell in row))

    if not rows:
        return MarkdownDoc(source_format="csv", warnings=("no rows parsed",))

    warnings: list[str] = []
    if truncated:
        warnings.append(f"truncated: only the first {MAX_ROWS} rows were converted")

    return MarkdownDoc(
        blocks=(Block(kind="table", rows=tuple(rows)),),
        title=path.stem,
        source_format="csv",
        warnings=tuple(warnings),
    )
