# Generated by scripts/oss/project_local_engine.py — DO NOT EDIT.
# Regenerate rather than patch; hand edits are rejected by the drift gate.
# SPDX-License-Identifier: Apache-2.0

"""Delimited text to ``MarkdownDoc``, as a single table.

The delimiter is sniffed from the start of the file rather than assumed to be a
comma, so tab- and semicolon-separated exports read correctly without the caller
having to say which they have.

Needs no optional dependency — this extractor works on a bare install.

Large files are truncated at a row cap, which the caller may raise, lower or
lift entirely. The cap counts DATA rows: the header is not charged to it, so a
cap of 5,000 converts 5,000 rows of data and the warning reports that same
number.
"""

from __future__ import annotations

import csv
from pathlib import Path

from convilyn.local._engine.markdown.model import Block, MarkdownDoc
from convilyn.local._engine.markdown.text import read_text_file

MAX_ROWS = 5_000

_SNIFF_BYTES = 8_192


def _dialect(sample: str) -> type[csv.Dialect] | csv.Dialect:
    try:
        return csv.Sniffer().sniff(sample, delimiters=",;\t|")
    except csv.Error:
        return csv.excel


def extract(path: Path, *, max_rows: int = MAX_ROWS) -> MarkdownDoc:
    """Read a delimited-text file into one table block.

    The first row becomes the table header, matching what a reader expects of a
    spreadsheet export. Very large files are truncated at a row cap and the returned
    document says so in its warnings rather than silently losing the tail.

    ``max_rows`` is how many DATA rows to read, not counting the header. It defaults
    to a cap that keeps a runaway file from rendering into a Markdown table no
    reader can open; pass a smaller number to sample the head of a large export, or
    ``0`` to read the whole thing. ``0`` is the caller asserting they want it — half
    a million rows will be rendered on request. A negative value raises
    ``ValueError`` rather than being clamped, since no reading of it is the one the
    caller meant.
    """
    if max_rows < 0:
        raise ValueError(f"max_rows must be 0 (no limit) or a positive row count, not {max_rows}")

    raw = read_text_file(path)
    if not raw.strip():
        return MarkdownDoc(source_format="csv", warnings=("empty CSV",))

    reader = csv.reader(raw.splitlines(), dialect=_dialect(raw[:_SNIFF_BYTES]))

    rows: list[tuple[str, ...]] = []
    truncated = False
    for index, row in enumerate(reader):
        if max_rows and index > max_rows:
            truncated = True
            break
        rows.append(tuple(cell.strip() for cell in row))

    if not rows:
        return MarkdownDoc(source_format="csv", warnings=("no rows parsed",))

    warnings: list[str] = []
    if truncated:
        warnings.append(f"truncated: only the first {max_rows} data rows were converted")

    return MarkdownDoc(
        blocks=(Block(kind="table", rows=tuple(rows)),),
        source_format="csv",
        warnings=tuple(warnings),
    )
