# Generated by scripts/oss/project_local_engine.py — DO NOT EDIT.
# Regenerate rather than patch; hand edits are rejected by the drift gate.
# SPDX-License-Identifier: Apache-2.0

"""Word documents to ``MarkdownDoc``.

Structure comes from the document's own styles rather than from guesswork:
heading levels are read from the paragraph style, and list items from the
numbering style, so a document that was written with real headings converts with
real headings.

Body content is walked in document order, which is what keeps a table between
two paragraphs in the place its author put it. Images are lifted out with their
alt text where the document carries any.
"""

from __future__ import annotations

import logging
from collections.abc import Iterator
from pathlib import Path
from typing import Any

from convilyn.local._engine.markdown.image_collector import ImageCollector
from convilyn.local._engine.markdown.model import (
    Block,
    ExtractedImage,
    MarkdownDoc,
)

logger = logging.getLogger(__name__)

_BULLET_STYLES = ("list bullet", "list paragraph")
_NUMBER_STYLES = ("list number",)


def _iter_body(document: Any) -> Iterator[tuple[str, Any]]:
    from docx.oxml.ns import qn
    from docx.table import Table
    from docx.text.paragraph import Paragraph

    for child in document.element.body.iterchildren():
        if child.tag == qn("w:p"):
            yield "p", Paragraph(child, document)
        elif child.tag == qn("w:tbl"):
            yield "tbl", Table(child, document)


def _heading_level(style_name: str) -> int | None:
    lowered = style_name.lower().strip()
    if lowered == "title":
        return 1
    if not lowered.startswith("heading"):
        return None
    tail = lowered.removeprefix("heading").strip()
    if tail.isdigit():
        return min(max(int(tail), 1), 6)
    return None


def _list_kind(paragraph: Any, style_name: str) -> tuple[bool, bool]:
    lowered = style_name.lower()
    if any(lowered.startswith(s) for s in _NUMBER_STYLES):
        return True, True
    if any(lowered.startswith(s) for s in _BULLET_STYLES):
        return True, False
    try:
        numbering = paragraph._p.pPr is not None and paragraph._p.pPr.numPr is not None
    except AttributeError:
        numbering = False
    return numbering, False


def _paragraph_images(
    paragraph: Any,
    document: Any,
    collector: ImageCollector,
) -> list[ExtractedImage]:
    from docx.oxml.ns import qn

    out: list[ExtractedImage] = []
    for blip in paragraph._p.iter(qn("a:blip")):
        rel_id = blip.get(qn("r:embed"))
        if not rel_id:
            continue
        try:
            part = document.part.related_parts[rel_id]
            data = part.blob
            media_type = part.content_type
        except (KeyError, AttributeError) as exc:
            logger.debug("docx image part %s unreadable (%s)", rel_id, exc)
            collector.note_unreadable()
            continue

        image = collector.collect(data, media_type, alt_text=_alt_text(blip))
        if image is not None:
            out.append(image)
    return out


def _alt_text(blip: Any) -> str:
    from docx.oxml.ns import qn

    for ancestor in blip.iterancestors():
        for prop in ancestor.iter(qn("wp:docPr")):
            return (prop.get("descr") or prop.get("name") or "").strip()
    return ""


def _table_rows(table: Any) -> tuple[tuple[str, ...], ...]:
    return tuple(tuple(cell.text.strip() for cell in row.cells) for row in table.rows)


def extract(path: Path) -> MarkdownDoc:
    """Read a Word document into a ``MarkdownDoc``.

    Paragraph styles map to headings, numbered and bulleted styles to list items,
    and tables to table blocks. Text in a paragraph style the mapping does not
    recognise becomes a paragraph rather than being dropped.
    """
    import docx

    document = docx.Document(str(path))
    blocks: list[Block] = []
    collector = ImageCollector()

    for kind, item in _iter_body(document):
        if kind == "tbl":
            rows = _table_rows(item)
            if rows:
                blocks.append(Block(kind="table", rows=rows))
            continue

        try:
            style_name = item.style.name or ""
        except AttributeError:
            style_name = ""

        for image in _paragraph_images(item, document, collector):
            blocks.append(Block(kind="image", image=image))

        text = item.text.strip()
        if not text:
            continue

        level = _heading_level(style_name)
        if level is not None:
            blocks.append(Block(kind="heading", text=text, level=level))
            continue

        is_list, ordered = _list_kind(item, style_name)
        if is_list:
            blocks.append(Block(kind="list_item", text=text, ordered=ordered))
            continue

        blocks.append(Block(kind="paragraph", text=text))

    return MarkdownDoc(
        blocks=tuple(blocks),
        source_format="docx",
        warnings=(),
        image_triage=collector.triage,
    )
