# Generated by scripts/oss/project_local_engine.py — DO NOT EDIT.
# Regenerate rather than patch; hand edits are rejected by the drift gate.
# SPDX-License-Identifier: Apache-2.0

"""Deciding when a line of a PDF is a heading.

A PDF records no headings, so the judgement is inferred from two things the file
does carry: how large a line is set relative to the document's body text, and
what the line says. Both are pure functions of values the extractor has already
read.
"""

from __future__ import annotations

import re
from collections import Counter

HEADING_RATIO = 1.15

HEADING_TIERS = ((1.9, 1), (1.6, 2), (1.35, 3), (HEADING_RATIO, 4))


def body_size(all_lines: list[tuple[str, float, float]]) -> float:
    """The document's body text size: the most common line size, not the mean.

    A mean is dragged upward by one large title on a page of ordinary prose, and a
    body size that is too large stops every real heading from standing out. Taken
    across the whole document, because a two-line sidebar has no meaningful
    population of its own.
    """
    sizes = Counter(round(line[1], 1) for line in all_lines if line[1] > 0)
    if not sizes:
        return 0.0
    return sizes.most_common(1)[0][0]


BARE_NUMBER = re.compile(r"^[\d\s]+$")


def is_bare_number(text: str) -> bool:
    """Whether the whole line is a number.

    Such a line is never a heading, whatever its size. A page number, a contents
    column and a figure label all reach the size test the same way, and a heading
    whose entire text is a number is not an outline entry anything can navigate by.
    The text is kept as a paragraph, so a document whose sections genuinely are
    numbers loses the outline entry rather than the content.
    """
    return bool(BARE_NUMBER.match(text))


def heading_level(size: float, body: float) -> int | None:
    """The heading level a line's size earns, or nothing when it earns none."""
    if body <= 0 or size <= 0:
        return None
    ratio = size / body
    for threshold, level in HEADING_TIERS:
        if ratio >= threshold:
            return level
    return None
