# Generated by scripts/oss/project_local_engine.py — DO NOT EDIT.
# Regenerate rather than patch; hand edits are rejected by the drift gate.
# SPDX-License-Identifier: Apache-2.0

"""Shape-based structure guesses, shared by the extractors that need them.

Some sources carry no style information at all — plain text, and PDF pages whose
text was drawn without a heading font. For those, the only signal available is
the shape of the line itself.
"""

from __future__ import annotations

import re

_MAX_HEADING_CHARS = 80

_NUMBERED_PREFIX = re.compile(r"^\d+\.")

_HEADING_STARTS = ("Chapter", "Section", "Part", "Introduction", "Conclusion")


def looks_like_heading(text: str) -> bool:
    """True when a line of unstyled text is probably a heading.

    Deliberately conservative. A false positive turns a sentence into a heading,
    which is more visibly wrong in the output than a heading left as a paragraph.
    """
    if len(text) > _MAX_HEADING_CHARS:
        return False

    if text.isupper() and len(text) > 5:
        return True

    if _NUMBERED_PREFIX.match(text):
        return True

    return any(text.startswith(word) for word in _HEADING_STARTS)
