# Generated by scripts/oss/project_local_engine.py — DO NOT EDIT.
# Regenerate rather than patch; hand edits are rejected by the drift gate.
# SPDX-License-Identifier: Apache-2.0

"""Image triage and identity, shared by the extractors that pull images out.

Two questions come up for every image in a document, and neither is answered by
looking at its bytes.

**Is this the same picture as one already seen?** Bytes are the weakest possible
answer: re-encoding the same logo at a different quality changes every byte and
nothing a reader would notice. Identity here is a digest of the image's
normalised pixels, so the same picture recognises itself across re-encodings.

**Is it worth carrying at all?** Documents are full of spacers, rules, bullets
and single-colour blocks. Those are answered by cheap measurements — pixel area,
byte size, aspect ratio, and how many distinct colours the image contains — each
with a threshold that errs toward keeping an image rather than discarding
content.

Uses Pillow, and only when there is an image to look at: importing this module
does not require it. An extractor whose document contains no images never
touches it.
"""

from __future__ import annotations

import hashlib
import io
import logging
from dataclasses import dataclass

logger = logging.getLogger(__name__)

_DEDUP_GRID = (16, 16)

_TRIAGE_GRID = (32, 32)

MIN_PIXEL_AREA = 4_096
MIN_BYTE_SIZE = 2_048
MAX_ASPECT_RATIO = 8.0
MIN_DISTINCT_COLOURS = 8

MAX_IMAGES_INSPECTED = 200

_EXT_BY_MEDIA_TYPE = {
    "image/png": "png",
    "image/jpeg": "jpg",
    "image/gif": "gif",
    "image/webp": "webp",
    "image/bmp": "bmp",
    "image/tiff": "tiff",
    "image/jp2": "jp2",
    "image/jpx": "jpx",
}

RENDERABLE_MEDIA_TYPES = frozenset(
    {"image/png", "image/jpeg", "image/gif", "image/webp", "image/bmp"}
)


@dataclass(frozen=True)
class ImageFacts:
    """The measurements taken from one image."""

    dedup_key: str
    width: int | None = None
    height: int | None = None
    distinct_colours: int | None = None
    decoded: bool = False


def extension_for(media_type: str) -> str:
    """The conventional file extension for a media type, e.g. ``png`` for ``image/png``."""
    return _EXT_BY_MEDIA_TYPE.get(media_type, "bin")


def asset_name(index: int, media_type: str) -> str:
    """The filename an extracted image is stored under.

    Stable for a given index and media type, and what ``render`` writes into the
    image link.
    """
    return f"img-{index:04d}.{extension_for(media_type)}"


def inspect(data: bytes) -> ImageFacts:
    """Measure an image's dimensions, colour variety and normalised-pixel digest."""
    try:
        from PIL import Image

        with Image.open(io.BytesIO(data)) as handle:
            rgb = handle.convert("RGB")
            width, height = rgb.size

            grid = rgb.resize(_DEDUP_GRID, Image.Resampling.BOX)
            key = hashlib.sha256(bytes(b >> 4 for b in grid.tobytes())).hexdigest()

            thumb = rgb.resize(_TRIAGE_GRID, Image.Resampling.NEAREST)
            max_colours = _TRIAGE_GRID[0] * _TRIAGE_GRID[1]
            palette = thumb.getcolors(maxcolors=max_colours)
            colours = max_colours if palette is None else len(palette)

        return ImageFacts(
            dedup_key=key,
            width=width,
            height=height,
            distinct_colours=colours,
            decoded=True,
        )
    except Exception as exc:
        logger.debug("image triage decode failed (%s); falling back to byte hash", exc)
        return ImageFacts(dedup_key=hashlib.sha256(data).hexdigest())


def to_deliverable(data: bytes, media_type: str) -> tuple[bytes, str]:
    """Re-encode an image to PNG when its format is not one a viewer renders.

    Documents carry pictures in formats that are perfectly valid and that nothing
    opens by double-clicking — JPEG 2000 above all, which publishing tools emit
    routinely and no browser displays. Extracting such an image faithfully still
    leaves the reader with a file they cannot look at.

    Returns the bytes and the media type to store, unchanged for a format that is
    already renderable and unchanged again when the decode fails. Either way the
    delivered file's extension describes its actual contents.

    PNG rather than JPEG, because these images frequently carry an alpha channel
    and JPEG has nowhere to put it.
    """
    if media_type in RENDERABLE_MEDIA_TYPES:
        return data, media_type

    try:
        from PIL import Image

        with Image.open(io.BytesIO(data)) as handle:
            handle.load()
            converted = handle.convert("RGBA" if "A" in handle.getbands() else "RGB")
            buffer = io.BytesIO()
            converted.save(buffer, format="PNG", optimize=True)
        return buffer.getvalue(), "image/png"
    except Exception as exc:
        logger.warning(
            "could not re-encode a %s image to PNG (%s); delivering the original, "
            "which may not open in a browser",
            media_type,
            exc,
        )
        return data, media_type


def is_decorative(facts: ImageFacts, byte_size: int) -> bool:
    """True when an image is almost certainly a spacer, rule, bullet or solid block.

    Thresholds err toward keeping: wrongly discarding a real figure loses content,
    while wrongly keeping a divider costs one line of Markdown.
    """
    if not facts.decoded or facts.width is None or facts.height is None:
        return False

    if byte_size < MIN_BYTE_SIZE:
        return True

    area = facts.width * facts.height
    if area < MIN_PIXEL_AREA:
        return True

    longest, shortest = max(facts.width, facts.height), min(facts.width, facts.height)
    if shortest > 0 and (longest / shortest) > MAX_ASPECT_RATIO:
        return True

    if facts.distinct_colours is not None and facts.distinct_colours < MIN_DISTINCT_COLOURS:
        return True

    return False
