# Generated by scripts/oss/project_local_engine.py — DO NOT EDIT.
# Regenerate rather than patch; hand edits are rejected by the drift gate.
# SPDX-License-Identifier: Apache-2.0

"""The image protocol a document extractor follows, owned in one place.

Pulling images out of a document is the same six steps whatever the format:
respect a per-document decode budget, measure the image, decide whether it is
furniture rather than content, recognise it if it has been seen before, give it
a stable filename, and remember what was left out. Only the first step differs
between a PDF, a Word file and a slide deck — how you get from the container to
the bytes.

This module holds the five steps that do not differ. The extractors keep the one
that does.

It also keeps the accounting. A conversion silently dropping pictures is worse
than one that drops them and says so: the counts it gathers travel on the
document model and surface in the conversion result, so "the file had twelve
images and the Markdown has nine" is always answerable.
"""

from __future__ import annotations

from convilyn.local._engine.markdown import images as img
from convilyn.local._engine.markdown.model import ExtractedImage, ImageTriage


class ImageCollector:
    """Gathers one document's images, applying the shared rules and tallying what was
    left out.
    """

    def __init__(self) -> None:
        self._seen: dict[str, str] = {}
        self._inspected = 0
        self._decorative = 0
        self._over_cap = 0
        self._unreadable = 0

    @property
    def at_cap(self) -> bool:
        """Whether the per-document inspection budget is used up.

        Worth asking when a caller can cheaply stop looking — abandoning a page walk,
        for instance. Purely an optimisation: :meth:`collect` enforces the budget on its
        own, so nothing breaks if you never ask.
        """
        return self._inspected >= img.MAX_IMAGES_INSPECTED

    def collect(
        self,
        data: bytes,
        media_type: str,
        *,
        alt_text: str = "",
    ) -> ExtractedImage | None:
        """Takes one image's bytes and returns it as part of the document, or ``None`` if
        it is not carried.

        ``None`` covers two different outcomes — measured and judged furniture, or past
        the inspection budget and never measured. A caller skips either way; the
        distinction is kept in the tally, because a reader can act on it.
        """
        if self.at_cap:
            self._over_cap += 1
            return None
        self._inspected += 1

        facts = img.inspect(data)
        if img.is_decorative(facts, len(data)):
            self._decorative += 1
            return None

        data, media_type = img.to_deliverable(data, media_type)

        name = self._seen.get(facts.dedup_key)
        if name is None:
            name = img.asset_name(len(self._seen) + 1, media_type)
            self._seen[facts.dedup_key] = name

        return ExtractedImage(
            data=data,
            media_type=media_type,
            asset_name=name,
            dedup_key=facts.dedup_key,
            width=facts.width,
            height=facts.height,
            alt_text=alt_text,
        )

    def note_over_cap(self) -> None:
        """Records an image reached past the decode cap, without decoding it.

        The counterpart to `at_cap`. Reaching an image's bytes is what runs its decode,
        so a caller that asks first pays nothing for the pictures beyond the cap — but
        it still has to say what it skipped, or the cap becomes exactly the silent kind
        of loss the triage counts exist to end.
        """
        self._over_cap += 1

    def note_unreadable(self) -> None:
        """Records an image reference whose bytes could not be read.

        Extractors already carry on past these, which is right — one unreadable picture
        should not fail a conversion. Telling the collector keeps the whole tally in one
        place.
        """
        self._unreadable += 1

    @property
    def triage(self) -> ImageTriage:
        """The counts so far, ready to travel on the document."""
        return ImageTriage(
            inspected=self._inspected,
            dropped_decorative=self._decorative,
            dropped_over_cap=self._over_cap,
            dropped_unreadable=self._unreadable,
        )
