# Generated by scripts/oss/project_local_engine.py — DO NOT EDIT.
# Regenerate rather than patch; hand edits are rejected by the drift gate.
# SPDX-License-Identifier: Apache-2.0

"""Reading order for a page that is not one column.

A PDF stores glyph positions, not paragraphs, and nothing in the file says where
one column ends and the next begins. Grouping words into lines by their vertical
position alone therefore assumes the page has a single column — and where that
is wrong, two columns are welded together line by line before anything else gets
a chance to look at the text.

This module runs first and returns regions in reading order. Everything else —
line grouping, paragraph reflow, heading detection — happens inside a region.

The algorithm is recursive XY-cut (Nagy, Seth & Viswanathan, 1984): project the
boxes onto each axis, cut at the widest run of background, recurse, and emit
left-to-right for a vertical cut and top-to-bottom for a horizontal one. It
needs only bounding boxes, so it works on what the text extractor already
produces and adds no dependency.

A page with no qualifying gap comes back as a single region, which is the same
result as not running it at all. That is deliberate: the pass is safe to apply
to every document rather than to the ones somebody guessed would need it.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any, TypeVar

MIN_COLUMN_GAP_RATIO = 0.8

MIN_BAND_GAP_RATIO = 1.2

MAX_CUT_DEPTH = 12

Box = TypeVar("Box", bound=Mapping[str, Any])


def _background_runs(
    boxes: Sequence[Box],
    low_key: str,
    high_key: str,
) -> list[tuple[float, float]]:
    spans = sorted((float(b[low_key]), float(b[high_key])) for b in boxes)
    runs: list[tuple[float, float]] = []
    reach = spans[0][1]
    for low, high in spans[1:]:
        if low > reach:
            runs.append((reach, low))
        reach = max(reach, high)
    return runs


def _best_run(runs: Sequence[tuple[float, float]], threshold: float) -> tuple[float, float] | None:
    qualifying = [run for run in runs if run[1] - run[0] >= threshold]
    return max(qualifying, key=lambda run: run[1] - run[0]) if qualifying else None


def order_regions(
    boxes: Sequence[Box],
    *,
    unit: float,
    _depth: int = 0,
) -> list[list[Box]]:
    """Group boxes into regions and return them in reading order.

    Takes anything carrying `x0`, `x1`, `top` and `bottom`. Words, table bounding
    boxes and figures may be mixed freely — a table passed as one box is treated as
    indivisible, so no cut runs through the middle of one.

    Returns a list of regions, each a list of the boxes inside it. Empty input
    returns no regions rather than one empty region.
    """
    items = list(boxes)
    if len(items) <= 1 or unit <= 0 or _depth >= MAX_CUT_DEPTH:
        return [items] if items else []

    column = _best_run(_background_runs(items, "x0", "x1"), MIN_COLUMN_GAP_RATIO * unit)
    band = _best_run(_background_runs(items, "top", "bottom"), MIN_BAND_GAP_RATIO * unit)
    if column is None and band is None:
        return [items]

    column_score = (column[1] - column[0]) / (MIN_COLUMN_GAP_RATIO * unit) if column else 0.0
    band_score = (band[1] - band[0]) / (MIN_BAND_GAP_RATIO * unit) if band else 0.0

    if column is not None and column_score >= band_score:
        split = (column[0] + column[1]) / 2
        near = [b for b in items if float(b["x1"]) <= split]
        far = [b for b in items if float(b["x1"]) > split]
    elif band is not None:
        split = (band[0] + band[1]) / 2
        near = [b for b in items if float(b["bottom"]) <= split]
        far = [b for b in items if float(b["bottom"]) > split]
    else:
        return [items]

    return order_regions(near, unit=unit, _depth=_depth + 1) + order_regions(
        far, unit=unit, _depth=_depth + 1
    )


def median_height(boxes: Sequence[Box]) -> float:
    """The median box height, which is the `unit` the thresholds are expressed in.

    Passing a measured length rather than a number of points is what makes the
    thresholds independent of font size, paper size and rasterisation density: the
    same layout at twice the scale yields the same regions.

    Median rather than mean, because one full-page figure would drag a mean far
    enough to disable both thresholds — and a page whose thresholds are too large is
    one this module silently does nothing to.
    """
    heights = sorted(float(b["bottom"]) - float(b["top"]) for b in boxes)
    if not heights:
        return 0.0
    return heights[len(heights) // 2]
