# Generated by scripts/oss/project_local_engine.py — DO NOT EDIT.
# Regenerate rather than patch; hand edits are rejected by the drift gate.
# SPDX-License-Identifier: Apache-2.0

"""The intermediate document model every extractor produces.

Extractors do not emit Markdown text. They emit this model, and ``render`` is
the single place that turns it into Markdown. Two things follow from that split,
and both are the reason it exists.

The first is that escaping has exactly one implementation. When each format's
extractor writes its own Markdown, each one grows its own opinion about pipes
inside table cells and underscores inside identifiers, and they drift apart.

The second is that the model is a stable thing to work with. A caller who wants
to inspect a document's structure, filter it, or transform it before rendering
can do so against ordinary frozen dataclasses, without going near a parser.

Everything is frozen. Values cross the extract-then-render pipeline, so a
transform returns new objects (``dataclasses.replace``) rather than mutating one
that another caller is holding.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal

BlockKind = Literal[
    "heading",
    "paragraph",
    "list_item",
    "table",
    "code",
    "quote",
    "image",
    "page_break",
]


@dataclass(frozen=True)
class ExtractedImage:
    """One image lifted out of a source document.

    ``dedup_key`` is a digest of the image's normalised pixels, not of its bytes:
    the same picture re-encoded twice has different bytes and the same appearance.
    Two entries sharing a ``dedup_key`` are the same picture.

    ``asset_name`` is assigned at extraction time and is what ``render`` writes into
    the link target. Images sharing a ``dedup_key`` share an ``asset_name``, so a
    logo repeated on forty pages is stored once and linked forty times.

    ``description`` is never filled in by this engine, which does no image analysis.
    It is yours to populate — from your own captioning model, from a manifest, from
    anything — before calling ``render``, which will place it under the image as a
    caption. Leave it ``None`` and the image renders with its alt text alone.
    """

    data: bytes
    media_type: str
    asset_name: str
    dedup_key: str
    width: int | None = None
    height: int | None = None
    alt_text: str = ""
    description: str | None = None


@dataclass(frozen=True)
class Block:
    """One renderable unit.

    A single dataclass with optional fields rather than a class hierarchy: the
    variants share no behaviour and are pattern-matched in exactly one place, so a
    hierarchy would buy an abstraction with a single consumer.
    """

    kind: BlockKind
    text: str = ""
    level: int = 0
    ordered: bool = False
    rows: tuple[tuple[str, ...], ...] = ()
    language: str = ""
    image: ExtractedImage | None = None


@dataclass(frozen=True)
class ImageTriage:
    """What the image pass left out of the document, and why.

    An extractor does not carry every picture it meets. Some are furniture — icons,
    spacers, rules — and are judged not worth carrying; some sit past the
    per-document limit on how many images are decoded at all; some are references
    the container could not resolve into bytes. The three are counted separately
    because they call for different responses: a filtering threshold you may
    disagree with, a document larger than the inspection budget, and a broken input.

    Nothing here is rendered. The Markdown stays clean and the counts travel
    alongside it, so a caller can tell the reader what is missing.
    """

    inspected: int = 0
    dropped_decorative: int = 0
    dropped_over_cap: int = 0
    dropped_unreadable: int = 0

    @property
    def dropped(self) -> int:
        """Every image the document contained and the model does not, whatever the reason."""
        return self.dropped_decorative + self.dropped_over_cap + self.dropped_unreadable


@dataclass(frozen=True)
class MarkdownDoc:
    """A whole document, ready to render.

    ``warnings`` carries a short machine-readable vocabulary (``layout_degraded``,
    ``best_effort``, and similar) describing where the extractor had to guess. They
    are advisory: a document with warnings still rendered.
    """

    blocks: tuple[Block, ...] = ()
    title: str | None = None
    source_format: str = ""
    warnings: tuple[str, ...] = field(default_factory=tuple)
    image_triage: ImageTriage = field(default_factory=ImageTriage)

    @property
    def images(self) -> tuple[ExtractedImage, ...]:
        """Every image block's image, in document order, including repeats."""
        return tuple(b.image for b in self.blocks if b.kind == "image" and b.image is not None)

    @property
    def unique_images(self) -> tuple[ExtractedImage, ...]:
        """One entry per distinct ``dedup_key``, first occurrence winning.

        This is the set to iterate when doing per-image work, because processing a
        repeated logo once rather than forty times is usually the whole saving.
        """
        seen: set[str] = set()
        out: list[ExtractedImage] = []
        for image in self.images:
            if image.dedup_key not in seen:
                seen.add(image.dedup_key)
                out.append(image)
        return tuple(out)
