# Generated by scripts/oss/project_local_engine.py — DO NOT EDIT.
# Regenerate rather than patch; hand edits are rejected by the drift gate.
# SPDX-License-Identifier: Apache-2.0

"""PDF to ``MarkdownDoc``.

A PDF has no headings, no lists and no paragraphs — it has glyphs at
coordinates. Structure has to be inferred, and this module infers it from two
signals that are actually present in the file.

The first is font size. Lines are grouped into rows, the body text size is taken
as the most common size in the document, and a line set noticeably larger than
that becomes a heading, with the heading level following how much larger it is.

The second is table geometry, which the underlying library detects from ruling
lines and text alignment. Text falling inside a detected table is claimed by
that table rather than being emitted twice as loose paragraphs.

Embedded images are extracted where the PDF stores them as image objects. A
page-count cap bounds the work a very large document can cause and is reported
in the returned document's warnings when it applies.

Structure recovered this way is a best-effort reading of a format that did not
record it, and the returned document says so.
"""

from __future__ import annotations

import logging
import re
from collections import Counter
from pathlib import Path
from typing import Any

from convilyn.local._engine.markdown.heuristics import (
    SENTENCE_END,
    has_cjk,
    looks_like_heading,
)
from convilyn.local._engine.markdown.image_collector import ImageCollector
from convilyn.local._engine.markdown.model import (
    Block,
    ExtractedImage,
    MarkdownDoc,
)

logger = logging.getLogger(__name__)

MAX_PAGES = 500

_HEADING_RATIO = 1.15

_HEADING_TIERS = ((1.6, 2), (1.35, 3), (_HEADING_RATIO, 4))

_LINE_TOLERANCE = 2.0


_SENTENCE_END = SENTENCE_END + "：:"

_BULLET = re.compile(r"^(?:[-]\s*|[•▪●○◦‧·※∙]\s*|[–—-]\s+)")


def _cluster_rows(words: list[dict]) -> list[list[dict]]:
    rows: list[list[dict]] = []
    for word in sorted(words, key=lambda w: w["top"]):
        if rows and word["top"] - rows[-1][0]["top"] <= _LINE_TOLERANCE:
            rows[-1].append(word)
        else:
            rows.append([word])
    return rows


def _join(left: str, right: str) -> str:
    if not left:
        return right
    if not right:
        return left
    if has_cjk(left[-1]) or has_cjk(right[0]):
        return left + right
    return f"{left} {right}"


def _continues(previous: tuple[str, float, bool], size: float, body: float) -> bool:
    text, previous_size, _ = previous
    if not text:
        return False
    if round(previous_size, 1) != round(size, 1):
        return False
    if body > 0 and previous_size >= body * _HEADING_RATIO:
        return False
    return text[-1] not in _SENTENCE_END


def _merge_wrapped(lines: list[tuple[str, float]], body: float) -> list[tuple[str, float, bool]]:
    merged: list[tuple[str, float, bool]] = []
    for text, size in lines:
        bullet = bool(_BULLET.match(text))
        content = _BULLET.sub("", text, count=1) if bullet else text
        if merged and not bullet and _continues(merged[-1], size, body):
            previous_text, previous_size, previous_bullet = merged[-1]
            merged[-1] = (_join(previous_text, content), previous_size, previous_bullet)
        else:
            merged.append((content, size, bullet))
    return merged


def _lines_with_sizes(page: Any, table_boxes: list[tuple]) -> list[tuple[str, float]]:
    try:
        words = page.extract_words(extra_attrs=["size"])
    except Exception as exc:
        logger.debug("pdf word extraction failed on a page (%s)", exc)
        return []

    kept = [w for w in words if not _in_any_box(w, table_boxes)]

    lines: list[tuple[str, float]] = []
    for row in _cluster_rows(kept):
        row = sorted(row, key=lambda w: w["x0"])
        text = " ".join(w["text"] for w in row).strip()
        if not text:
            continue
        sizes = sorted(float(w.get("size") or 0.0) for w in row)
        lines.append((text, sizes[len(sizes) // 2]))
    return lines


def _in_any_box(word: dict, boxes: list[tuple]) -> bool:
    for x0, top, x1, bottom in boxes:
        if (
            word["x0"] >= x0
            and word["x1"] <= x1
            and word["top"] >= top
            and word["bottom"] <= bottom
        ):
            return True
    return False


def _body_size(all_lines: list[tuple[str, float]]) -> float:
    sizes = Counter(round(size, 1) for _, size in all_lines if size > 0)
    if not sizes:
        return 0.0
    return sizes.most_common(1)[0][0]


def _heading_level(size: float, body: float) -> int | None:
    if body <= 0 or size <= 0:
        return None
    ratio = size / body
    for threshold, level in _HEADING_TIERS:
        if ratio >= threshold:
            return level
    return None


def _extract_images(path: Path, collector: ImageCollector) -> dict[int, list[ExtractedImage]]:
    per_page: dict[int, list[ExtractedImage]] = {}

    try:
        from pypdf import PdfReader

        reader = PdfReader(str(path))
        for index, page in enumerate(reader.pages[:MAX_PAGES]):
            for item in page.images:
                if collector.at_cap:
                    return per_page

                image = collector.collect(item.data, _media_type_for(item.name))
                if image is not None:
                    per_page.setdefault(index, []).append(image)
    except Exception as exc:
        logger.debug("pdf image extraction failed (%s); continuing without images", exc)

    return per_page


def _media_type_for(name: str) -> str:
    suffix = Path(name or "").suffix.lower().lstrip(".")
    return {
        "png": "image/png",
        "jpg": "image/jpeg",
        "jpeg": "image/jpeg",
        "gif": "image/gif",
        "webp": "image/webp",
        "tiff": "image/tiff",
        "bmp": "image/bmp",
    }.get(suffix, "image/png")


def extract(path: Path) -> MarkdownDoc:
    """Read a PDF into a ``MarkdownDoc``.

    Headings are inferred from relative font size, tables from detected geometry,
    and everything else becomes paragraphs in reading order.
    """
    import pdfplumber

    warnings: list[str] = []
    collector = ImageCollector()
    page_images = _extract_images(path, collector)

    pages: list[tuple[list[tuple[str, float]], list[list[list[str | None]]]]] = []
    with pdfplumber.open(path) as pdf:
        total = len(pdf.pages)
        if total > MAX_PAGES:
            warnings.append(f"truncated: only the first {MAX_PAGES} of {total} pages converted")

        for page in pdf.pages[:MAX_PAGES]:
            try:
                found = page.find_tables()
                boxes = [t.bbox for t in found]
                tables = [t.extract() for t in found]
            except Exception as exc:
                logger.debug("pdf table extraction failed on a page (%s)", exc)
                boxes, tables = [], []
            pages.append((_lines_with_sizes(page, boxes), tables))

    body = _body_size([line for lines, _ in pages for line in lines])

    blocks: list[Block] = []
    for index, (lines, tables) in enumerate(pages):
        if index:
            blocks.append(Block(kind="page_break"))

        for text, size, bullet in _merge_wrapped(lines, body):
            if not text:
                continue
            if bullet:
                blocks.append(Block(kind="list_item", text=text))
                continue
            level = _heading_level(size, body)
            if level is None and looks_like_heading(text):
                level = 3
            if level is not None:
                blocks.append(Block(kind="heading", text=text, level=level))
            else:
                blocks.append(Block(kind="paragraph", text=text))

        for table in tables:
            rows = tuple(tuple((cell or "").strip() for cell in row) for row in table if row)
            if rows:
                blocks.append(Block(kind="table", rows=rows))

        for image in page_images.get(index, ()):
            blocks.append(Block(kind="image", image=image))

    if not blocks:
        warnings.append("no text layer found — this PDF is probably a scan")

    warnings.append("best_effort: PDF carries no structure; headings inferred from font size")

    return MarkdownDoc(
        blocks=tuple(blocks),
        source_format="pdf",
        warnings=tuple(warnings),
        image_triage=collector.triage,
    )
