# Generated by scripts/oss/project_local_engine.py — DO NOT EDIT.
# Regenerate rather than patch; hand edits are rejected by the drift gate.
# SPDX-License-Identifier: Apache-2.0

"""PDF to ``MarkdownDoc``.

A PDF has no headings, no lists and no paragraphs — it has glyphs at
coordinates. Structure has to be inferred, and this module infers it from two
signals that are actually present in the file.

The first is font size. Lines are grouped into rows, the body text size is taken
as the most common size in the document, and a line set noticeably larger than
that becomes a heading, with the heading level following how much larger it is.

The second is table geometry, which the underlying library detects from ruling
lines and text alignment. Text falling inside a detected table is claimed by
that table rather than being emitted twice as loose paragraphs.

Embedded images are extracted where the PDF stores them as image objects. A
page-count cap bounds the work a very large document can cause and is reported
in the returned document's warnings when it applies.

Structure recovered this way is a best-effort reading of a format that did not
record it, and the returned document says so.
"""

from __future__ import annotations

import logging
import re
from collections import Counter
from collections.abc import Iterator
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from convilyn.local._engine.markdown.heuristics import (
    SENTENCE_END,
    has_cjk,
    looks_like_heading,
)
from convilyn.local._engine.markdown.image_collector import ImageCollector
from convilyn.local._engine.markdown.layout import median_height, order_regions
from convilyn.local._engine.markdown.model import (
    Block,
    ExtractedImage,
    MarkdownDoc,
)

logger = logging.getLogger(__name__)

MAX_PAGES = 500

_HEADING_RATIO = 1.15

_HEADING_TIERS = ((1.6, 2), (1.35, 3), (_HEADING_RATIO, 4))

_LINE_TOLERANCE = 2.0

_DEDUPE_TOLERANCE = 1

_PLACED_BLOCK = "_placed_block"

MIN_TABLE_ROWS = 2
MIN_TABLE_COLUMNS = 2


_SENTENCE_END = SENTENCE_END + "：:"

_BULLET = re.compile(r"^(?:[-]\s*|[•▪●○◦‧·※∙]\s*|[–—-]\s+)")


def _cluster_rows(words: list[dict]) -> list[list[dict]]:
    rows: list[list[dict]] = []
    for word in sorted(words, key=lambda w: w["top"]):
        if rows and word["top"] - rows[-1][0]["top"] <= _LINE_TOLERANCE:
            rows[-1].append(word)
        else:
            rows.append([word])
    return rows


def _join(left: str, right: str) -> str:
    if not left:
        return right
    if not right:
        return left
    if has_cjk(left[-1]) or has_cjk(right[0]):
        return left + right
    return f"{left} {right}"


def _continues(previous: tuple[str, float, bool], size: float, body: float) -> bool:
    text, previous_size, _ = previous
    if not text:
        return False
    if round(previous_size, 1) != round(size, 1):
        return False
    if body > 0 and previous_size >= body * _HEADING_RATIO:
        return False
    return text[-1] not in _SENTENCE_END


def _merge_wrapped(lines: list[tuple[str, float]], body: float) -> list[tuple[str, float, bool]]:
    merged: list[tuple[str, float, bool]] = []
    for text, size in lines:
        bullet = bool(_BULLET.match(text))
        content = _BULLET.sub("", text, count=1) if bullet else text
        if merged and not bullet and _continues(merged[-1], size, body):
            previous_text, previous_size, previous_bullet = merged[-1]
            merged[-1] = (_join(previous_text, content), previous_size, previous_bullet)
        else:
            merged.append((content, size, bullet))
    return merged


def _lines_from_words(words: list[dict]) -> list[tuple[str, float, float]]:
    lines: list[tuple[str, float, float]] = []
    for row in _cluster_rows(words):
        ordered = sorted(row, key=lambda w: w["x0"])
        text = " ".join(w["text"] for w in ordered).strip()
        if not text:
            continue
        sizes = sorted(float(w.get("size") or 0.0) for w in ordered)
        lines.append((text, sizes[len(sizes) // 2], min(float(w["top"]) for w in ordered)))
    return lines


def _in_any_box(word: dict, boxes: list[tuple]) -> bool:
    for x0, top, x1, bottom in boxes:
        if (
            word["x0"] >= x0
            and word["x1"] <= x1
            and word["top"] >= top
            and word["bottom"] <= bottom
        ):
            return True
    return False


def _body_size(all_lines: list[tuple[str, float, float]]) -> float:
    sizes = Counter(round(line[1], 1) for line in all_lines if line[1] > 0)
    if not sizes:
        return 0.0
    return sizes.most_common(1)[0][0]


def _heading_level(size: float, body: float) -> int | None:
    if body <= 0 or size <= 0:
        return None
    ratio = size / body
    for threshold, level in _HEADING_TIERS:
        if ratio >= threshold:
            return level
    return None


def _image_sources_by_page(path: Path) -> dict[int, dict[str, Any]]:
    per_page: dict[int, dict[str, Any]] = {}

    try:
        from pypdf import PdfReader

        reader = PdfReader(str(path))
        for index, page in enumerate(reader.pages[:MAX_PAGES]):
            for item in page.images:
                per_page.setdefault(index, {})[item.name.rsplit(".", 1)[0]] = item
    except Exception as exc:
        logger.debug("pdf image extraction failed (%s); continuing without images", exc)

    return per_page


def _collect(item: Any, collector: ImageCollector) -> ExtractedImage | None:
    if collector.at_cap:
        collector.note_over_cap()
        return None

    try:
        data = item.data
    except Exception as exc:
        logger.warning("a pdf image stream could not be decoded (%s); skipping it", exc)
        collector.note_unreadable()
        return None
    return collector.collect(data, _media_type_for(item.name))


def _media_type_for(name: str) -> str:
    suffix = Path(name or "").suffix.lower().lstrip(".")
    return {
        "png": "image/png",
        "jpg": "image/jpeg",
        "jpeg": "image/jpeg",
        "gif": "image/gif",
        "webp": "image/webp",
        "tiff": "image/tiff",
        "tif": "image/tiff",
        "bmp": "image/bmp",
        "jp2": "image/jp2",
        "jpx": "image/jpx",
        "jpf": "image/jpx",
    }.get(suffix, "application/octet-stream")


@dataclass(frozen=True)
class _Region:
    lines: tuple[tuple[str, float, float], ...] = ()
    placed: tuple[tuple[float, Block], ...] = ()


def _table_block(rows: list[list[str | None]]) -> Block | None:
    cleaned = tuple(tuple((cell or "").strip() for cell in row) for row in rows if row)
    if len(cleaned) < MIN_TABLE_ROWS:
        return None
    if max((len(row) for row in cleaned), default=0) < MIN_TABLE_COLUMNS:
        return None
    if not any(cell for row in cleaned for cell in row):
        return None
    return Block(kind="table", rows=cleaned)


def _placed_images(
    placements: list[dict],
    image_sources: dict[str, Any],
    collector: ImageCollector,
) -> tuple[list[dict], list[Block]]:
    boxes: list[dict] = []
    seen: dict[str, ExtractedImage | None] = {}

    for placement in placements:
        name = str(placement.get("name") or "")
        item = image_sources.get(name)
        if item is None:
            collector.note_unreadable()
            continue
        if name not in seen:
            seen[name] = _collect(item, collector)
        image = seen[name]
        if image is None:
            continue
        boxes.append(
            {
                "x0": placement["x0"],
                "x1": placement["x1"],
                "top": placement["top"],
                "bottom": placement["bottom"],
                _PLACED_BLOCK: Block(kind="image", image=image),
            }
        )

    trailing: list[Block] = []
    for name, item in image_sources.items():
        if name in seen:
            continue
        image = _collect(item, collector)
        if image is not None:
            trailing.append(Block(kind="image", image=image))

    return boxes, trailing


def _column_overlap(box: dict, bounds: tuple[float, float, float, float]) -> float:
    x0, _, x1, _ = bounds
    return min(float(box["x1"]), x1) - max(float(box["x0"]), x0)


def _vertical_distance(box: dict, bounds: tuple[float, float, float, float]) -> float:
    _, top, _, bottom = bounds
    if float(box["bottom"]) < top:
        return top - float(box["bottom"])
    if float(box["top"]) > bottom:
        return float(box["top"]) - bottom
    return 0.0


def _assign_images(
    regions: list[list[dict]],
    images: list[dict],
) -> tuple[dict[int, list[tuple[float, Block]]], list[Block]]:
    bounds = [
        (
            min((float(b["x0"]) for b in region), default=0.0),
            min((float(b["top"]) for b in region), default=0.0),
            max((float(b["x1"]) for b in region), default=0.0),
            max((float(b["bottom"]) for b in region), default=0.0),
        )
        for region in regions
    ]

    assigned: dict[int, list[tuple[float, Block]]] = {}
    leftovers: list[Block] = []
    for image in images:
        best_index, best_distance = -1, 0.0
        for index, rectangle in enumerate(bounds):
            if _column_overlap(image, rectangle) <= 0:
                continue
            distance = _vertical_distance(image, rectangle)
            if best_index < 0 or distance < best_distance:
                best_index, best_distance = index, distance
        if best_index < 0:
            leftovers.append(image[_PLACED_BLOCK])
        else:
            assigned.setdefault(best_index, []).append((float(image["top"]), image[_PLACED_BLOCK]))
    return assigned, leftovers


def _read_page(
    page: Any,
    image_sources: dict[str, Any],
    collector: ImageCollector,
) -> list[_Region]:
    placements = list(getattr(page, "images", None) or [])
    page = page.dedupe_chars(tolerance=_DEDUPE_TOLERANCE)

    try:
        found = page.find_tables()
        candidates = [(t.bbox, t.extract()) for t in found]
    except Exception as exc:
        logger.debug("pdf table extraction failed on a page (%s)", exc)
        candidates = []

    tables = [(bbox, block) for bbox, rows in candidates if (block := _table_block(rows))]

    try:
        words = page.extract_words(extra_attrs=["size"])
    except Exception as exc:
        logger.debug("pdf word extraction failed on a page (%s)", exc)
        words = []

    items: list[dict] = [w for w in words if not _in_any_box(w, [bbox for bbox, _ in tables])]
    for bbox, block in tables:
        x0, top, x1, bottom = bbox
        items.append(
            {"x0": x0, "x1": x1, "top": top, "bottom": bottom, _PLACED_BLOCK: block},
        )

    boxes, trailing = _placed_images(placements, image_sources, collector)

    grouped = order_regions(items, unit=median_height(items))
    assigned, unplaced = _assign_images(grouped, boxes)
    trailing.extend(unplaced)

    regions: list[_Region] = []
    for index, region in enumerate(grouped):
        placed = [(float(i["top"]), i[_PLACED_BLOCK]) for i in region if _PLACED_BLOCK in i]
        placed.extend(assigned.get(index, ()))
        placed.sort(key=lambda entry: entry[0])
        words_only = [i for i in region if _PLACED_BLOCK not in i]
        regions.append(_Region(lines=tuple(_lines_from_words(words_only)), placed=tuple(placed)))

    if trailing:
        regions.append(_Region(placed=tuple((0.0, block) for block in trailing)))
    return regions


def _chunk_at_blocks(
    region: _Region,
) -> Iterator[tuple[list[tuple[str, float, float]], Block | None]]:
    lines = sorted(region.lines, key=lambda line: line[2])
    cursor = 0
    for top, block in region.placed:
        chunk = [line for line in lines[cursor:] if line[2] < top]
        cursor += len(chunk)
        yield chunk, block
    yield lines[cursor:], None


def _region_blocks(region: _Region, body: float) -> list[Block]:
    blocks: list[Block] = []
    for chunk, placed in _chunk_at_blocks(region):
        for text, size, bullet in _merge_wrapped([(t, s) for t, s, _ in chunk], body):
            if not text:
                continue
            if bullet:
                blocks.append(Block(kind="list_item", text=text))
                continue
            level = _heading_level(size, body)
            if level is None and looks_like_heading(text):
                level = 3
            if level is not None:
                blocks.append(Block(kind="heading", text=text, level=level))
            else:
                blocks.append(Block(kind="paragraph", text=text))

        if placed is not None:
            blocks.append(placed)
    return blocks


def extract(path: Path) -> MarkdownDoc:
    """Read a PDF into a ``MarkdownDoc``.

    Headings are inferred from relative font size, tables from detected geometry,
    and everything else becomes paragraphs in reading order.
    """
    import pdfplumber

    warnings: list[str] = []
    collector = ImageCollector()
    image_sources = _image_sources_by_page(path)

    pages: list[list[_Region]] = []
    with pdfplumber.open(path) as pdf:
        total = len(pdf.pages)
        if total > MAX_PAGES:
            warnings.append(f"truncated: only the first {MAX_PAGES} of {total} pages converted")

        for index, page in enumerate(pdf.pages[:MAX_PAGES]):
            pages.append(_read_page(page, image_sources.get(index, {}), collector))

    body = _body_size([line for regions in pages for region in regions for line in region.lines])

    blocks: list[Block] = []
    for index, regions in enumerate(pages):
        if index:
            blocks.append(Block(kind="page_break"))

        for region in regions:
            blocks.extend(_region_blocks(region, body))

    if not blocks:
        warnings.append("no text layer found — this PDF is probably a scan")

    warnings.append("best_effort: PDF carries no structure; headings inferred from font size")

    return MarkdownDoc(
        blocks=tuple(blocks),
        source_format="pdf",
        warnings=tuple(warnings),
        image_triage=collector.triage,
    )
