# Generated by scripts/oss/project_local_engine.py — DO NOT EDIT.
# Regenerate rather than patch; hand edits are rejected by the drift gate.
# SPDX-License-Identifier: Apache-2.0

"""Presentations to ``MarkdownDoc``, one section per slide.

A slide's title placeholder becomes a heading and its body text becomes
paragraphs and list items, so the deck's outline survives. Speaker notes are
included after the slide's content, because they are usually where the actual
argument is written down.

Tables and pictures are carried across in slide order. A slide-count cap bounds
the work a very large deck can cause and is reported in the returned document's
warnings when it applies.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

from convilyn.local._engine.markdown.image_collector import ImageCollector
from convilyn.local._engine.markdown.model import (
    Block,
    ExtractedImage,
    MarkdownDoc,
)

logger = logging.getLogger(__name__)

MAX_SLIDES = 500


def _is_title(shape: Any, slide: Any) -> bool:
    try:
        return slide.shapes.title is not None and shape == slide.shapes.title
    except (AttributeError, ValueError):
        return False


def _table_rows(shape: Any) -> tuple[tuple[str, ...], ...]:
    return tuple(tuple(cell.text.strip() for cell in row.cells) for row in shape.table.rows)


def _picture(shape: Any, collector: ImageCollector) -> ExtractedImage | None:
    try:
        image = shape.image
        data = image.blob
        media_type = image.content_type
    except (AttributeError, ValueError, KeyError) as exc:
        logger.debug("pptx picture unreadable (%s)", exc)
        collector.note_unreadable()
        return None

    alt = ""
    try:
        alt = (shape._element._nvXxPr.cNvPr.get("descr") or "").strip()
    except AttributeError:
        alt = ""

    return collector.collect(data, media_type, alt_text=alt)


def _notes(slide: Any) -> str:
    try:
        if not slide.has_notes_slide:
            return ""
        return (slide.notes_slide.notes_text_frame.text or "").strip()
    except (AttributeError, ValueError):
        return ""


def extract(path: Path) -> MarkdownDoc:
    """Read a presentation into a ``MarkdownDoc``.

    Each slide contributes a heading (from its title, where it has one), its shapes
    in reading order, and its speaker notes.
    """
    from pptx import Presentation
    from pptx.enum.shapes import MSO_SHAPE_TYPE

    presentation = Presentation(str(path))
    blocks: list[Block] = []
    warnings: list[str] = []
    collector = ImageCollector()

    slides = list(presentation.slides)
    if len(slides) > MAX_SLIDES:
        warnings.append(f"truncated: only the first {MAX_SLIDES} of {len(slides)} slides converted")

    for number, slide in enumerate(slides[:MAX_SLIDES], start=1):
        if number > 1:
            blocks.append(Block(kind="page_break"))

        title_shape = None
        try:
            title_shape = slide.shapes.title
        except (AttributeError, ValueError):
            title_shape = None

        heading = (title_shape.text or "").strip() if title_shape is not None else ""
        blocks.append(Block(kind="heading", text=heading or f"Slide {number}", level=2))

        for shape in slide.shapes:
            if shape.shape_type == MSO_SHAPE_TYPE.PICTURE:
                image = _picture(shape, collector)
                if image is not None:
                    blocks.append(Block(kind="image", image=image))
                continue

            if getattr(shape, "has_table", False):
                rows = _table_rows(shape)
                if rows:
                    blocks.append(Block(kind="table", rows=rows))
                continue

            if not getattr(shape, "has_text_frame", False):
                continue
            if title_shape is not None and shape == title_shape:
                continue

            text_frame: Any = getattr(shape, "text_frame", None)
            if text_frame is None:
                continue

            for paragraph in text_frame.paragraphs:
                text = "".join(run.text for run in paragraph.runs).strip()
                if not text:
                    continue
                blocks.append(Block(kind="list_item", text=text, level=max(paragraph.level, 0)))

        notes = _notes(slide)
        if notes:
            blocks.append(Block(kind="quote", text=notes))

    return MarkdownDoc(
        blocks=tuple(blocks),
        source_format="pptx",
        warnings=tuple(warnings),
        image_triage=collector.triage,
    )
