# Generated by scripts/oss/project_local_engine.py — DO NOT EDIT.
# Regenerate rather than patch; hand edits are rejected by the drift gate.
# SPDX-License-Identifier: Apache-2.0

"""Source format to how it is read. The only dispatch in this package.

Two tables, both dictionaries rather than ``if``/``elif`` chains, because a
chain makes adding a format an edit to a decision tree whose ordering carries
meaning nobody wrote down. Here a format is a key.

The first table holds formats read directly. The second holds formats read
through a modern sibling: a legacy or OpenDocument file is converted once into
its Office Open XML counterpart by an external office suite, and the result then
runs through that counterpart's own extractor. One hop buys the whole
structure-aware path instead of a second, worse parser per legacy format.

A format in neither table is one this engine does not handle.

Extractors are imported lazily, inside their registry entry. Several pull heavy
optional dependencies, and a module-level import would make every caller pay for
every format whether or not they convert anything — including a caller who only
wants to ask which formats are supported.

This module answers what the engine *can* read. Whether a particular conversion
can run right now also depends on which optional dependencies are installed, and
for the bridged formats on whether an office suite is present;
``convilyn.local.capabilities()`` is what answers that.
"""

from __future__ import annotations

from collections.abc import Callable
from pathlib import Path
from typing import Literal, NamedTuple

from convilyn.local._engine.formats import DocumentFormat
from convilyn.local._engine.markdown.model import MarkdownDoc

Extractor = Callable[[Path], MarkdownDoc]

BridgeEngine = Literal["libreoffice", "calibre"]


class BridgeRoute(NamedTuple):
    """Read a format by converting it to ``bridge`` with ``engine`` first."""

    bridge: DocumentFormat
    engine: BridgeEngine


def _pdf(path: Path) -> MarkdownDoc:
    from convilyn.local._engine.markdown.pdf import extract

    return extract(path)


def _docx(path: Path) -> MarkdownDoc:
    from convilyn.local._engine.markdown.docx import extract

    return extract(path)


def _pptx(path: Path) -> MarkdownDoc:
    from convilyn.local._engine.markdown.pptx import extract

    return extract(path)


def _xlsx(path: Path) -> MarkdownDoc:
    from convilyn.local._engine.markdown.xlsx import extract

    return extract(path)


def _csv(path: Path) -> MarkdownDoc:
    from convilyn.local._engine.markdown.csv_ import extract

    return extract(path)


def _xml(path: Path) -> MarkdownDoc:
    from convilyn.local._engine.markdown.xml_ import extract

    return extract(path)


def _text(path: Path) -> MarkdownDoc:
    from convilyn.local._engine.markdown.text import extract

    return extract(path)


_EXTRACTORS: dict[DocumentFormat, Extractor] = {
    DocumentFormat.PDF: _pdf,
    DocumentFormat.DOCX: _docx,
    DocumentFormat.PPTX: _pptx,
    DocumentFormat.XLSX: _xlsx,
    DocumentFormat.CSV: _csv,
    DocumentFormat.XML: _xml,
    DocumentFormat.TXT: _text,
}


_BRIDGES: dict[DocumentFormat, BridgeRoute] = {
    DocumentFormat.DOC: BridgeRoute(DocumentFormat.DOCX, "libreoffice"),
    DocumentFormat.ODT: BridgeRoute(DocumentFormat.DOCX, "libreoffice"),
    DocumentFormat.RTF: BridgeRoute(DocumentFormat.DOCX, "libreoffice"),
    DocumentFormat.XLS: BridgeRoute(DocumentFormat.XLSX, "libreoffice"),
    DocumentFormat.ODS: BridgeRoute(DocumentFormat.XLSX, "libreoffice"),
    DocumentFormat.PPT: BridgeRoute(DocumentFormat.PPTX, "libreoffice"),
    DocumentFormat.ODP: BridgeRoute(DocumentFormat.PPTX, "libreoffice"),
    DocumentFormat.EPUB: BridgeRoute(DocumentFormat.DOCX, "calibre"),
    DocumentFormat.MOBI: BridgeRoute(DocumentFormat.DOCX, "calibre"),
    DocumentFormat.AZW3: BridgeRoute(DocumentFormat.DOCX, "calibre"),
}


def extractor_for(source: DocumentFormat) -> Extractor | None:
    """The native extractor for a format, or ``None`` if it needs a bridge."""
    return _EXTRACTORS.get(source)


def bridge_for(source: DocumentFormat) -> BridgeRoute | None:
    """How a format is bridged, or ``None`` if it needs no bridge.

    ``None`` from both this and ``extractor_for`` means the engine cannot read the
    format at all, which is what ``can_read`` answers directly.
    """
    return _BRIDGES.get(source)


def can_read(source: DocumentFormat) -> bool:
    """True when this engine can produce a document from the given source format."""
    return source in _EXTRACTORS or source in _BRIDGES
