# Generated by scripts/oss/project_local_engine.py — DO NOT EDIT.
# Regenerate rather than patch; hand edits are rejected by the drift gate.
# SPDX-License-Identifier: Apache-2.0

r"""``MarkdownDoc`` to GitHub-Flavoured Markdown. The only serializer.

Every extractor routes through here, which is what stops each format growing its
own half-right opinion about escaping.

## Escaping policy

Deliberately narrow. Over-escaping is not the safe choice — it produces
``\_\_init\_\_`` and ``C\:\\Users`` in technical documents, which corrupts the
content just as surely as a broken table, only less visibly.

So exactly the characters that would otherwise change the document's *structure*
are escaped: the backslash itself (first, or every later escape doubles), ``*``
and backtick, the square brackets that would open a link, ``<`` (which would
open raw HTML), and the line-leading characters that would start a block.

``<`` carries a second job. Text extracted from a document you did not write
must not be able to emit live markup into a file somebody else opens, and
escaping it is what closes that.

``_`` is deliberately **not** escaped. CommonMark does not honour intra-word
underscores, so ``snake_case_name`` is already safe, and escaping it is the
single most common way converters mangle code-bearing prose.

## Images

``ASSET_DIR`` is the directory name used in image links. Paths are relative, so
a rendered document and its extracted images stay valid wherever the pair is
moved to, and offline.
"""

from __future__ import annotations

import re

from convilyn.local._engine.markdown.model import Block, MarkdownDoc

_INLINE_SPECIAL = re.compile(r"([\\*`\[\]<])")

_LINE_START_MARKER = re.compile(r"^(\s*)([#>|+-]|\d+\.)")

ASSET_DIR = "assets"

_MAX_HEADING_LEVEL = 6


def escape_inline(text: str) -> str:
    """Escape the structural Markdown characters inside a line of prose."""
    return _INLINE_SPECIAL.sub(r"\\\1", text)


def escape_block_text(text: str) -> str:
    """Escape a whole paragraph: inline specials, plus line-leading block markers."""
    escaped = escape_inline(text)
    return "\n".join(_LINE_START_MARKER.sub(r"\1\\\2", line) for line in escaped.split("\n"))


def escape_cell(text: str) -> str:
    """Escape a table cell.

    A GFM cell cannot contain a raw ``|`` (it would end the cell) or a newline (it
    would end the row), and there is no escape for the newline — so it becomes
    ``<br>``, which is the one place this module emits HTML on purpose.
    """
    cell = escape_inline(text.strip())
    cell = cell.replace("|", "\\|")
    return re.sub(r"\r?\n", "<br>", cell)


def _render_table(rows: tuple[tuple[str, ...], ...]) -> str:
    if not rows:
        return ""

    width = max(len(row) for row in rows)
    padded = [tuple(row) + ("",) * (width - len(row)) for row in rows]

    header, *body = padded
    lines = [
        "| " + " | ".join(escape_cell(c) for c in header) + " |",
        "| " + " | ".join(["---"] * width) + " |",
    ]
    lines += ["| " + " | ".join(escape_cell(c) for c in row) + " |" for row in body]
    return "\n".join(lines)


def _render_image(block: Block) -> str:
    image = block.image
    if image is None:
        return ""

    alt = escape_cell(image.alt_text or image.description or "")
    out = f"![{alt}]({ASSET_DIR}/{image.asset_name})"
    if image.description:
        quoted = "\n".join(f"> {line}" for line in image.description.strip().split("\n"))
        out = f"{out}\n\n{quoted}"
    return out


def _render_block(block: Block) -> str:
    if block.kind == "heading":
        level = min(max(block.level, 1), _MAX_HEADING_LEVEL)
        return f"{'#' * level} {escape_inline(block.text.strip())}"

    if block.kind == "list_item":
        indent = "  " * max(block.level, 0)
        marker = "1." if block.ordered else "-"
        return f"{indent}{marker} {escape_inline(block.text.strip())}"

    if block.kind == "table":
        return _render_table(block.rows)

    if block.kind == "code":
        return f"```{block.language}\n{block.text.rstrip()}\n```"

    if block.kind == "quote":
        return "\n".join(f"> {escape_inline(line)}" for line in block.text.strip().split("\n"))

    if block.kind == "image":
        return _render_image(block)

    if block.kind == "page_break":
        return "---"

    return escape_block_text(block.text.strip())


def render(doc: MarkdownDoc) -> str:
    """Serialize a document to Markdown: blank-line separated, one trailing newline.

    Consecutive list items are not blank-line separated, because GFM would then
    render a "loose" list with every item wrapped in a paragraph, which is not what
    the source document meant.
    """
    parts: list[str] = []
    if doc.title:
        parts.append(f"# {escape_inline(doc.title.strip())}")

    previous: Block | None = None
    for block in doc.blocks:
        text = _render_block(block)
        if not text:
            continue
        tight = previous is not None and previous.kind == "list_item" and block.kind == "list_item"
        if parts and tight:
            parts[-1] = f"{parts[-1]}\n{text}"
        else:
            parts.append(text)
        previous = block

    return "\n\n".join(parts).strip() + "\n"
