# Generated by scripts/oss/project_local_engine.py — DO NOT EDIT.
# Regenerate rather than patch; hand edits are rejected by the drift gate.
# SPDX-License-Identifier: Apache-2.0

"""Which detected grids become tables, and which words a table has already spoken for.

A PDF does not say where its tables are. A detector proposes grids, and two
decisions follow: whether a proposed grid is really a table, and — once it is —
which words on the page that table has therefore already emitted, so they are
not printed a second time as ordinary prose.

Both are here because they are one decision seen from either end. Getting either
wrong produces the same class of defect: text appearing where it does not belong.
"""

from __future__ import annotations

import logging
from typing import Any

from convilyn.local._engine.markdown.layout import (
    MIN_COLUMN_GAP_RATIO,
    background_runs,
    median_height,
)
from convilyn.local._engine.markdown.model import Block

logger = logging.getLogger(__name__)

_TEXT_STRATEGY = {"vertical_strategy": "text", "horizontal_strategy": "text"}

MIN_TABLE_ROWS = 2
MIN_TABLE_COLUMNS = 2

_OVERHANG_TOLERANCE_RATIO = 0.5


def table_block(rows: list[list[str | None]]) -> Block | None:
    """A table block for this grid, or nothing when the grid cannot be one.

    Rejection is not cosmetic. Decorative rounded boxes and framed callouts are
    detected as grids on real documents, and reading one as a table splits sentences
    across cell walls that were never there. Returning nothing sends the text back to
    the prose stream intact, which is the better failure.
    """
    cleaned = tuple(tuple((cell or "").strip() for cell in row) for row in rows if row)
    if len(cleaned) < MIN_TABLE_ROWS:
        return None
    if max((len(row) for row in cleaned), default=0) < MIN_TABLE_COLUMNS:
        return None
    if not any(cell for row in cleaned for cell in row):
        return None
    return Block(kind="table", rows=cleaned)


def in_any_box(word: dict, boxes: list[tuple]) -> bool:
    """True when this word falls inside one of these boxes and must not repeat as prose.

    Only accepted tables contribute a box. So a true answer means the word's text has
    already been written out inside a table, and letting it through to the prose
    stream as well would print it twice — once in the table, once loose, where it
    also welds onto whatever paragraph follows.
    """
    wx0, wx1 = float(word["x0"]), float(word["x1"])
    wtop, wbottom = float(word["top"]), float(word["bottom"])
    slack = (wbottom - wtop) * _OVERHANG_TOLERANCE_RATIO
    for x0, top, x1, bottom in boxes:
        if wx1 - wx0 > x1 - x0 or wbottom - wtop > bottom - top:
            continue
        if (
            wx0 >= x0 - slack
            and wx1 <= x1 + slack
            and wtop >= top - slack
            and wbottom <= bottom + slack
        ):
            return True
    return False


def _splits_a_word(rows: list[list[str | None]], page_words: set[str]) -> bool:
    for row in rows:
        for cell in row:
            if not cell:
                continue
            if any(token not in page_words for token in cell.split()):
                return True
    return False


def _has_real_gutters(words: list[dict], columns: int) -> bool:
    if len(words) < 2:
        return False
    unit = median_height(words)
    if unit <= 0:
        return False
    runs = background_runs(words, "x0", "x1")
    gutters = sum(1 for low, high in runs if high - low >= MIN_COLUMN_GAP_RATIO * unit)
    return gutters >= columns - 1


def _is_tabular(row: list[str | None]) -> bool:
    return sum(1 for cell in row if (cell or "").strip()) >= MIN_TABLE_COLUMNS


def _trim_to_tabular_rows(table: Any) -> tuple[tuple, list[list[str | None]]] | None:
    rows = table.extract()
    tabular = [i for i, row in enumerate(rows) if _is_tabular(row)]
    if not tabular:
        return None

    first, last = tabular[0], tabular[-1]
    kept = [row for row in rows[first : last + 1] if any((cell or "").strip() for cell in row)]
    bbox = (
        table.bbox[0],
        table.rows[first].bbox[1],
        table.bbox[2],
        table.rows[last].bbox[3],
    )
    return bbox, kept


def detect_tables(page: Any) -> list[tuple[tuple, Block]]:
    """Every table this page really has, each with the area of the page it occupies.

    Ruled tables are found first, because a table drawn with lines is stated rather
    than guessed at. Only on a page where nothing was drawn does a second pass look
    for a table held together by alignment alone — the borderless kind, common in
    financial statements and slide exports.

    That second pass is the reason this function is careful rather than eager. A
    detector working from spacing will happily read an ordinary page of prose as a
    grid, inventing column boundaries through the middle of words; measured on one,
    it produced a 35-by-8 table whose cells held fragments like `The quarterl` and
    `y re`. So its output is checked before it is believed: a candidate is refused
    outright if any text it claims is not a whole word on the page, and it is
    narrowed to the rows that actually span columns, so a title above the table and
    a paragraph below it stay where they were written.

    A page whose only drawn grid was refused as a table has already been answered,
    and the second pass does not reopen the question. Nor does a page the reader
    cannot parse: a malformed page yields no tables and is read as prose rather than
    failing the conversion.
    """
    try:
        return _detect(page)
    except Exception as exc:
        logger.debug("pdf table extraction failed on a page (%s)", exc)
        return []


def _detect(page: Any) -> list[tuple[tuple, Block]]:
    drawn = list(page.find_tables())
    ruled = [(t.bbox, block) for t in drawn if (block := table_block(t.extract()))]
    if ruled:
        return ruled

    words = page.extract_words()
    page_words = {word["text"] for word in words}
    found: list[tuple[tuple, Block]] = []
    for candidate in page.find_tables(table_settings=_TEXT_STRATEGY):
        trimmed = _trim_to_tabular_rows(candidate)
        if trimmed is None:
            continue
        bbox, rows = trimmed
        if _splits_a_word(rows, page_words):
            continue
        in_span = [
            w for w in words if bbox[1] <= (float(w["top"]) + float(w["bottom"])) / 2 <= bbox[3]
        ]
        if not _has_real_gutters(in_span, max(len(row) for row in rows)):
            continue
        if (block := table_block(rows)) is not None:
            found.append((bbox, block))
    return found
