# Generated by scripts/oss/project_local_engine.py — DO NOT EDIT.
# Regenerate rather than patch; hand edits are rejected by the drift gate.
# SPDX-License-Identifier: Apache-2.0

"""Plain text to ``MarkdownDoc``.

The simplest extractor, and the reference shape for the others: read, split into
blocks, return the model. No Markdown is written here.
"""

from __future__ import annotations

from pathlib import Path

from convilyn.local._engine.markdown.heuristics import looks_like_heading
from convilyn.local._engine.markdown.model import Block, MarkdownDoc


def read_text_file(path: Path) -> str:
    """Read a text file, tolerating bytes that are not valid UTF-8.

    Falls back to latin-1, which cannot fail. A conversion should not stop because a
    document was saved in a legacy codepage; the worst outcome is a few mangled
    accented characters, which beats no output at all.
    """
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return path.read_text(encoding="latin-1")


def extract(path: Path) -> MarkdownDoc:
    """Read a text file into blank-line-separated paragraphs.

    Headings are inferred from line shape, since plain text carries no styling. The
    returned document always carries a ``best_effort`` warning for that reason.
    """
    raw = read_text_file(path)
    blocks: list[Block] = []

    for chunk in raw.split("\n\n"):
        text = chunk.strip()
        if not text:
            continue
        if looks_like_heading(text):
            blocks.append(Block(kind="heading", text=text, level=2))
        else:
            blocks.append(Block(kind="paragraph", text=text))

    return MarkdownDoc(
        blocks=tuple(blocks),
        source_format="txt",
        warnings=("best_effort: plain text carries no structure; headings are inferred",),
    )
