# Generated by scripts/oss/project_local_engine.py — DO NOT EDIT.
# Regenerate rather than patch; hand edits are rejected by the drift gate.
# SPDX-License-Identifier: Apache-2.0

"""Spreadsheets to ``MarkdownDoc``, one table per worksheet.

Each sheet becomes a heading followed by a table, so a multi-sheet workbook
reads as a document rather than as one undifferentiated grid.

Cells are read for their displayed value, not their formula: the point of a
Markdown rendering is what a person would see in the spreadsheet.

Per-sheet row, column and sheet-count caps keep a pathological workbook from
producing an unusable wall of Markdown; each one is reported in the returned
document's warnings when it applies.
"""

from __future__ import annotations

import logging
from datetime import date, datetime, time
from pathlib import Path
from typing import Any

from convilyn.local._engine.markdown.model import Block, MarkdownDoc

logger = logging.getLogger(__name__)

MAX_ROWS_PER_SHEET = 5_000
MAX_COLS = 100
MAX_SHEETS = 50


def _format(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, datetime):
        return value.date().isoformat() if value.time() == time(0, 0) else value.isoformat(" ")
    if isinstance(value, (date, time)):
        return value.isoformat()
    if isinstance(value, float) and value.is_integer():
        return str(int(value))
    return str(value).strip()


def _sheet_rows(sheet: Any) -> tuple[tuple[tuple[str, ...], ...], bool]:
    rows: list[tuple[str, ...]] = []
    truncated = False

    for raw in sheet.iter_rows(values_only=True):
        if len(rows) >= MAX_ROWS_PER_SHEET:
            truncated = True
            break
        cells = [_format(v) for v in raw[:MAX_COLS]]
        while cells and not cells[-1]:
            cells.pop()
        rows.append(tuple(cells))

    while rows and not any(rows[-1]):
        rows.pop()

    return tuple(rows), truncated


def extract(path: Path) -> MarkdownDoc:
    """Read a workbook into one table block per worksheet.

    Empty trailing rows and columns are trimmed, so a sheet with data in A1:C10 does
    not render as a table padded out to the spreadsheet's maximum extent.
    """
    import openpyxl

    workbook = openpyxl.load_workbook(str(path), read_only=True, data_only=True)
    blocks: list[Block] = []
    warnings: list[str] = []
    saw_value = False

    try:
        names = workbook.sheetnames
        if len(names) > MAX_SHEETS:
            warnings.append(
                f"truncated: only the first {MAX_SHEETS} of {len(names)} sheets converted"
            )

        for name in names[:MAX_SHEETS]:
            rows, truncated = _sheet_rows(workbook[name])
            blocks.append(Block(kind="heading", text=name, level=2))

            if not rows:
                blocks.append(Block(kind="paragraph", text="(empty sheet)"))
                continue

            saw_value = saw_value or any(any(cell for cell in row) for row in rows)
            blocks.append(Block(kind="table", rows=rows))
            if truncated:
                warnings.append(f"truncated: sheet {name!r} exceeded {MAX_ROWS_PER_SHEET} rows")
    finally:
        workbook.close()

    if blocks and not saw_value:
        warnings.append(
            "no cell values found — if this workbook is formula-only and has "
            "never been opened by Excel, it carries no cached results to read"
        )

    return MarkdownDoc(
        blocks=tuple(blocks),
        source_format="xlsx",
        warnings=tuple(warnings),
    )
