# Generated by scripts/oss/project_local_engine.py — DO NOT EDIT.
# Regenerate rather than patch; hand edits are rejected by the drift gate.
# SPDX-License-Identifier: Apache-2.0

"""XML to ``MarkdownDoc``, as a nested heading-and-paragraph outline.

Element names become headings and text content becomes paragraphs, so the shape
of the document survives into the Markdown rather than being flattened into one
blob.

Parsing goes through ``defusedxml``, which disables entity expansion and
external-entity resolution. XML from an untrusted source is a well-known way to
turn a parser into a file reader or a memory exhaustion, and the standard
library's default parser does not defend against it.

Depth and element-count caps bound the work a deeply nested or very large
document can cause; both are reported in the returned document's warnings when
they bite.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

from convilyn.local._engine.markdown.model import Block, MarkdownDoc

logger = logging.getLogger(__name__)

MAX_DEPTH = 6

MAX_ELEMENTS = 5_000


def _local_name(tag: Any) -> str:
    text = str(tag)
    return text.rsplit("}", 1)[-1] if "}" in text else text


def _walk(element: Any, depth: int, blocks: list[Block], budget: list[int]) -> None:
    if budget[0] <= 0:
        return
    budget[0] -= 1

    blocks.append(Block(kind="heading", text=_local_name(element.tag), level=min(depth, MAX_DEPTH)))

    if element.attrib:
        rows = [("attribute", "value")]
        rows += [(_local_name(k), str(v)) for k, v in element.attrib.items()]
        blocks.append(Block(kind="table", rows=tuple(tuple(r) for r in rows)))

    text = (element.text or "").strip()
    if text:
        blocks.append(Block(kind="paragraph", text=text))

    for child in list(element):
        _walk(child, depth + 1, blocks, budget)

        tail = (child.tail or "").strip()
        if tail:
            blocks.append(Block(kind="paragraph", text=tail))


def extract(path: Path) -> MarkdownDoc:
    """Read an XML file into a nested outline.

    Nesting depth becomes heading level, up to the depth cap. A document that hits
    either the depth or element cap still returns, with a warning saying so.
    """
    from defusedxml.ElementTree import ParseError, parse

    warnings: list[str] = []
    try:
        root = parse(str(path)).getroot()
    except ParseError as exc:
        return MarkdownDoc(source_format="xml", warnings=(f"malformed XML: {exc}",))
    except Exception as exc:
        logger.warning("xml parse rejected (%s)", exc)
        return MarkdownDoc(source_format="xml", warnings=(f"XML rejected: {exc}",))

    if root is None:
        return MarkdownDoc(source_format="xml", warnings=("XML has no root element",))

    blocks: list[Block] = []
    budget = [MAX_ELEMENTS]
    _walk(root, 1, blocks, budget)

    if budget[0] <= 0:
        warnings.append(f"truncated: only the first {MAX_ELEMENTS} elements were converted")

    return MarkdownDoc(
        blocks=tuple(blocks),
        title=_local_name(root.tag),
        source_format="xml",
        warnings=tuple(warnings),
    )
