# Generated by scripts/oss/project_local_engine.py — DO NOT EDIT.
# Regenerate rather than patch; hand edits are rejected by the drift gate.
# SPDX-License-Identifier: Apache-2.0

"""The document formats this engine can read.

``DocumentFormat`` is the vocabulary every other module in the engine speaks:
a route is a pair of these, and the registry is keyed by them. Values are the
lowercase file-extension spellings, so a member round-trips through a filename
without a translation table.
"""

from enum import Enum


class ImageFormat(str, Enum):
    """An image format, named by its usual file extension.

    Spellings that mean the same format — `jpeg` for `jpg`, `tif` for `tiff` — are
    resolved before they reach here; the member is the canonical one.

    As with `DocumentFormat`, membership means the format is *known*, not that this
    machine can read or write it. Several depend on a Pillow plugin that is not
    installed by default. Ask `convilyn.local.capabilities()`.
    """

    JPG = "jpg"
    PNG = "png"
    GIF = "gif"
    WEBP = "webp"
    TIFF = "tiff"
    BMP = "bmp"
    ICO = "ico"
    TGA = "tga"
    PCX = "pcx"
    PPM = "ppm"
    DDS = "dds"
    SGI = "sgi"
    XBM = "xbm"
    PDF = "pdf"

    AVIF = "avif"
    HEIC = "heic"
    JP2 = "jp2"

    PSD = "psd"
    SVG = "svg"
    DNG = "dng"
    CR2 = "cr2"
    NEF = "nef"
    EXR = "exr"
    HDR = "hdr"
    XPM = "xpm"
    PCD = "pcd"


class DocumentFormat(str, Enum):
    """A document format, named by its usual file extension.

    Membership here means the format is *known*, not that it can be read on this
    machine. Whether a given source can actually be converted depends on which
    optional dependencies are installed and, for the legacy and OpenDocument
    members, on whether an external office suite is available — ask
    ``convilyn.local.capabilities()`` rather than assuming.
    """

    DOCX = "docx"
    DOC = "doc"
    XLSX = "xlsx"
    XLS = "xls"
    PPTX = "pptx"
    PPT = "ppt"

    PDF = "pdf"

    ODT = "odt"
    ODS = "ods"
    ODP = "odp"

    TXT = "txt"
    RTF = "rtf"
    CSV = "csv"
    MD = "md"

    HTML = "html"
    XML = "xml"

    EPUB = "epub"
    MOBI = "mobi"
    AZW3 = "azw3"


IMAGE_FORMAT_ALIASES: dict[str, ImageFormat] = {
    "jpeg": ImageFormat.JPG,
    "jpe": ImageFormat.JPG,
    "jfif": ImageFormat.JPG,
    "jif": ImageFormat.JPG,
    "jfi": ImageFormat.JPG,
    "jps": ImageFormat.JPG,
    "tif": ImageFormat.TIFF,
    "heif": ImageFormat.HEIC,
    "dib": ImageFormat.BMP,
    "cur": ImageFormat.ICO,
    "pbm": ImageFormat.PPM,
    "pgm": ImageFormat.PPM,
    "pnm": ImageFormat.PPM,
    "rgb": ImageFormat.SGI,
    "rgba": ImageFormat.SGI,
    "bw": ImageFormat.SGI,
    "targa": ImageFormat.TGA,
    "jpeg2000": ImageFormat.JP2,
    "j2k": ImageFormat.JP2,
    "j2c": ImageFormat.JP2,
    "jpx": ImageFormat.JP2,
    "rgbe": ImageFormat.HDR,
}


__all__ = [
    "ImageFormat",
    "IMAGE_FORMAT_ALIASES",
    "DocumentFormat",
]
