# Generated by scripts/oss/project_local_engine.py — DO NOT EDIT.
# Regenerate rather than patch; hand edits are rejected by the drift gate.
# SPDX-License-Identifier: Apache-2.0

"""Page-level PDF operations: select, merge, rotate, compress, encrypt, burst.

Pure and synchronous. Every function reads local paths and writes to a path the
caller chose, so nothing here performs network access, holds state, or knows
where the document came from.

Page numbers are **1-based at this module's edge** and 0-based inside, matching
what a person types and what the underlying library indexes. `parse_pages` is
the only place that conversion happens.

## What is not here

Rasterising pages to images needs an external program (Poppler), where
everything in this module needs only the `pdf` extra. Recognising text in a
scan is OCR, which is a different capability again. Neither belongs to a page
operation, and neither is silently attempted.
"""

from __future__ import annotations

import io
from collections.abc import Sequence
from pathlib import Path

from pypdf import PdfReader, PdfWriter


class PdfOperationError(Exception):
    """An operation could not be performed on this document.

    Carries a sentence describing what was refused and why. Raised rather than
    returned so that a caller who ignores the possibility gets a stack trace
    instead of a wrong file.
    """


def parse_pages(spec: str) -> list[int]:
    """Turn a page-range string such as `"1-3,5,7-9"` into 0-based page indices.

    Accepts single pages, inclusive ranges, and comma-separated combinations of
    both. Whitespace around a part is ignored.

    Raises `ValueError` on a malformed part rather than skipping it: a typo in a
    page range that silently converts the wrong pages is worse than being told
    about it.
    """
    if not spec or not spec.strip():
        raise ValueError("Empty page range")

    indices: list[int] = []
    for raw in spec.split(","):
        part = raw.strip()
        if "-" in part:
            start_text, end_text = part.split("-", 1)
            start, end = _page_number(start_text, part), _page_number(end_text, part)
            if end < start:
                raise ValueError(f"Invalid range: {part!r} — the end comes before the start")
            indices.extend(range(start - 1, end))
        else:
            indices.append(_page_number(part, part) - 1)
    return indices


def _page_number(text: str, part: str) -> int:
    try:
        page = int(text.strip())
    except ValueError:
        raise ValueError(
            f"Invalid page range {part!r} — expected a page number like 3, or a range like 1-5"
        ) from None
    if page < 1:
        raise ValueError(f"Invalid page number {page} in {part!r} — pages are numbered from 1")
    return page


def _selected(reader: PdfReader, pages: str | None) -> list[int]:
    return parse_pages(pages) if pages else list(range(len(reader.pages)))


def _write(writer: PdfWriter, output: Path) -> Path:
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("wb") as handle:
        writer.write(handle)
    return output


def select(source: Path, output: Path, *, pages: str | None = None) -> Path:
    """Write the chosen pages into one new PDF.

    Without a range, every page is copied. Indices beyond the end of the document
    are ignored rather than refused, so `1-100` on a shorter file is a reasonable
    way to say "the rest". A selection that matches nothing at all is an error —
    it means none of what the caller asked for exists.
    """
    reader = PdfReader(source)
    writer = PdfWriter()
    for index in _selected(reader, pages):
        if 0 <= index < len(reader.pages):
            writer.add_page(reader.pages[index])

    if not writer.pages:
        raise PdfOperationError("No valid pages found for split")
    return _write(writer, output)


def merge(sources: Sequence[Path], output: Path) -> Path:
    """Concatenate several PDFs into one, in the order given."""
    if not sources:
        raise PdfOperationError("Merging needs at least one document")

    writer = PdfWriter()
    for source in sources:
        for page in PdfReader(source).pages:
            writer.add_page(page)
    return _write(writer, output)


def rotate(source: Path, output: Path, *, degrees: int = 90, pages: str | None = None) -> Path:
    """Rotate the chosen pages clockwise, copying the rest unchanged.

    Without a range, every page is rotated. The angle must be a quarter turn:
    other values produce a document most viewers render incorrectly, so they are
    refused here rather than left for the reader to discover.
    """
    if degrees % 90:
        raise PdfOperationError(f"Rotation must be a multiple of 90 degrees, got {degrees}")

    reader = PdfReader(source)
    chosen = set(parse_pages(pages)) if pages else None

    writer = PdfWriter()
    for index, page in enumerate(reader.pages):
        if chosen is None or index in chosen:
            page.rotate(degrees)
        writer.add_page(page)
    return _write(writer, output)


def compress(source: Path, output: Path) -> Path:
    """Recompress content streams losslessly.

    Text and vector artwork shrink. A scanned document does not, because its size
    is in the embedded images and this touches only the streams that describe the
    page. Nothing is re-encoded and no quality is lost, so the output renders
    identically to the input.
    """
    reader = PdfReader(source)
    writer = PdfWriter()
    for page in reader.pages:
        writer.add_page(page)
    for page in writer.pages:
        page.compress_content_streams()
    return _write(writer, output)


def encrypt(source: Path, output: Path, *, password: str) -> Path:
    """Write a copy that requires a password to open."""
    if not password:
        raise PdfOperationError("Password required for encryption")

    reader = PdfReader(source)
    writer = PdfWriter()
    for page in reader.pages:
        writer.add_page(page)
    writer.encrypt(password)
    return _write(writer, output)


def decrypt(source: Path, output: Path, *, password: str) -> Path:
    """Write a copy with the password removed.

    A document that is not encrypted is copied rather than refused — the caller
    asked for an unprotected file, and that is what they get. A wrong password is
    an error.
    """
    if not password:
        raise PdfOperationError("Password required for decryption")

    reader = PdfReader(source)
    if reader.is_encrypted and reader.decrypt(password) == 0:
        raise PdfOperationError("Incorrect password")

    writer = PdfWriter()
    for page in reader.pages:
        writer.add_page(page)
    return _write(writer, output)


def burst(source: Path, *, pages: str | None = None) -> list[tuple[str, bytes]]:
    """Split a document into one single-page PDF per page.

    Returns `(filename, bytes)` pairs rather than writing files, so the caller
    chooses the container: a directory of PDFs, a ZIP, or an upload. Names are
    zero-padded so that a directory listing sorts into page order.
    """
    reader = PdfReader(source)

    produced: list[tuple[str, bytes]] = []
    for index in _selected(reader, pages):
        if not 0 <= index < len(reader.pages):
            continue
        writer = PdfWriter()
        writer.add_page(reader.pages[index])
        buffer = io.BytesIO()
        writer.write(buffer)
        produced.append((f"page_{index + 1:03d}.pdf", buffer.getvalue()))

    if not produced:
        raise PdfOperationError("No valid pages found to extract")
    return produced


def extract_text(source: Path, *, pages: str | None = None) -> str:
    """Read the text layer, joined with a blank line between pages.

    Returns an empty string for a scanned document, which has no text layer. That
    is the honest answer rather than a failure: recovering glyphs from an image is
    OCR, and this does not attempt it.
    """
    reader = PdfReader(source)

    parts: list[str] = []
    for index in _selected(reader, pages):
        if 0 <= index < len(reader.pages):
            text = reader.pages[index].extract_text()
            if text:
                parts.append(text)
    return "\n\n".join(parts)


def page_count(source: Path) -> int:
    """How many pages the document has."""
    return len(PdfReader(source).pages)


__all__ = [
    "PdfOperationError",
    "burst",
    "compress",
    "decrypt",
    "encrypt",
    "extract_text",
    "merge",
    "page_count",
    "parse_pages",
    "rotate",
    "select",
]
