# Generated by scripts/oss/project_local_engine.py — DO NOT EDIT.
# Regenerate rather than patch; hand edits are rejected by the drift gate.
# SPDX-License-Identifier: Apache-2.0

"""Image transformation and saving.

Loading is the caller's job, because it is source-specific: a vector file needs
a rasteriser and a camera RAW needs a decoder, and neither is something every
caller should pay for. What happens afterwards is universal — normalise the
colour mode for what the target format can actually store, resize if asked, and
save with that format's options — and that is what lives here.

Everything takes an open image and returns an open image or writes a file.
Nothing here reads configuration or performs I/O of its own beyond that write.

## The pixel budget

`MAX_IMAGE_PIXELS` is a decompression-bomb ceiling. A hundred-kilobyte PNG can
declare itself tens of thousands of pixels square and exhaust memory during
decode, before any check on the decoded image gets a chance to run — so the
guard reads the header first. Pillow has its own limit for the same attack, and
it is set from this constant so the two cannot disagree.

The default is sized for a personal machine: comfortably above any camera you
own, and low enough that a crafted file cannot take your session with it. Raise
it yourself if you genuinely work with larger images.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from convilyn.local._engine.formats import ImageFormat
from convilyn.local._engine.image.pil_formats import get_pil_format_name

MAX_IMAGE_PIXELS = 40_000_000

_NO_ALPHA_FORMATS = frozenset({ImageFormat.JPG, ImageFormat.PDF, ImageFormat.PCX, ImageFormat.PPM})

_CMYK_CAPABLE = frozenset({ImageFormat.JPG, ImageFormat.TIFF})

_DEEP_CAPABLE = frozenset({ImageFormat.PNG, ImageFormat.TIFF})

_PALETTE_CAPABLE = frozenset({ImageFormat.GIF, ImageFormat.PNG})

_REQUIRED_MODES: dict[ImageFormat, tuple[str, ...]] = {
    ImageFormat.XBM: ("1",),
    ImageFormat.PCX: ("RGB", "L", "P"),
    ImageFormat.SGI: ("RGB", "RGBA", "L"),
    ImageFormat.PPM: ("RGB",),
}

_ICO_MAX_EDGE = 256


class ImageTooLargeError(ValueError):
    """The image exceeds the pixel budget and will not be decoded further."""


def assert_within_pixel_budget(width: int, height: int) -> None:
    """Refuse an image whose decoded size would exceed the budget.

    Checked from the header dimensions, before the pixels are materialised — which
    is the whole point. Checking afterwards is checking after the damage.
    """
    total = width * height
    if total > MAX_IMAGE_PIXELS:
        raise ImageTooLargeError(
            f"Image is {total:,} pixels ({width}×{height}); the maximum is {MAX_IMAGE_PIXELS:,}."
        )


def apply_pillow_limit() -> None:
    """Point Pillow's own decompression-bomb guard at the same constant.

    Two guards, one number. Pillow's catches what gets past the header check — a
    truncated or lying header; this module's produces the error a caller can read.
    """
    from PIL import Image

    Image.MAX_IMAGE_PIXELS = MAX_IMAGE_PIXELS


def normalise_mode(img: Any, target_format: ImageFormat) -> tuple[Any, list[str]]:
    """Convert an image into a colour mode the target format can store.

    Returns the image and any warnings worth passing on: a conversion that loses
    information (CMYK to RGB, 16-bit to 8-bit) is something a caller should be able
    to report, not a silent downgrade.

    Order matters. The general information-preserving conversions run first, then
    the per-format encoder constraints, because the second set assumes the first has
    already happened.
    """
    from PIL import Image

    warnings: list[str] = []

    if img.mode == "CMYK" and target_format not in _CMYK_CAPABLE:
        img = img.convert("RGB")
        warnings.append("CMYK color mode converted to RGB")

    if img.mode in ("I;16", "I;16L", "I;16B") and target_format not in _DEEP_CAPABLE:
        img = img.convert("L")
        warnings.append("16-bit image converted to 8-bit")

    if img.mode == "P" and target_format not in _PALETTE_CAPABLE:
        img = img.convert("RGB")

    if target_format in _NO_ALPHA_FORMATS and img.mode in ("RGBA", "LA"):
        background = Image.new("RGB", img.size, (255, 255, 255))
        alpha_band = 3 if img.mode == "RGBA" else 1
        background.paste(img, mask=img.split()[alpha_band])
        img = background

    if target_format == ImageFormat.ICO:
        if max(img.size) > _ICO_MAX_EDGE:
            img.thumbnail((_ICO_MAX_EDGE, _ICO_MAX_EDGE), Image.Resampling.LANCZOS)
        if img.mode != "RGBA":
            img = img.convert("RGBA")

    required = _REQUIRED_MODES.get(target_format)
    if required and img.mode not in required:
        img = img.convert(required[0])

    return img, warnings


def resize(img: Any, width: int | None, height: int | None, maintain_aspect: bool) -> Any:
    """Resize an image, optionally preserving its aspect ratio.

    With both dimensions given and the aspect preserved, the image is fitted inside
    the box rather than stretched to it.
    """
    from PIL import Image

    original_width, original_height = img.size

    if maintain_aspect:
        if width and height:
            ratio = min(width / original_width, height / original_height)
            new_width = int(original_width * ratio)
            new_height = int(original_height * ratio)
        elif width:
            ratio = width / original_width
            new_width = width
            new_height = int(original_height * ratio)
        elif height:
            ratio = height / original_height
            new_width = int(original_width * ratio)
            new_height = height
        else:
            return img
    else:
        new_width = width or original_width
        new_height = height or original_height

    return img.resize((new_width, new_height), Image.Resampling.LANCZOS)


def save(img: Any, path: Path, target_format: ImageFormat, options: dict[str, Any]) -> None:
    """Write an image in the given format.

    Two formats need more than a name and a dictionary of options — PDF must be RGB,
    and JPEG 2000 spells its quality parameters differently from everything else —
    so both are handled here rather than at every call site.
    """
    if target_format == ImageFormat.PDF:
        if img.mode != "RGB":
            img = img.convert("RGB")
        img.save(path, "PDF", **options)
        return

    if target_format == ImageFormat.JP2:
        jp2_options: dict[str, Any] = {}
        quality = options.get("quality")
        if quality is not None:
            jp2_options["quality_mode"] = "rates"
            jp2_options["quality_layers"] = [quality]
        img.save(path, format="JPEG2000", **jp2_options)
        return

    img.save(path, format=get_pil_format_name(target_format), **options)


def save_options(format: ImageFormat, quality: int | None) -> dict[str, Any]:
    """The Pillow `save()` parameters for a format, at a requested quality.

    Quality does not mean the same thing everywhere: JPEG and WebP take a 0-100
    quality, PNG takes a compression level, and the lossless formats take neither.
    This is where that is decided once.
    """
    options: dict[str, Any] = {}

    if format == ImageFormat.JPG:
        options["quality"] = quality if quality is not None else 90
        options["optimize"] = True
        options["progressive"] = True

    elif format == ImageFormat.PNG:
        if quality is not None:
            compress_level = max(0, min(9, int((100 - quality) / 11)))
            options["compress_level"] = compress_level
        else:
            options["compress_level"] = 6
        options["optimize"] = True

    elif format == ImageFormat.WEBP:
        if quality is not None:
            options["quality"] = quality
            options["lossless"] = quality == 100
        else:
            options["quality"] = 85
            options["lossless"] = False
        options["method"] = 6

    elif format == ImageFormat.GIF:
        options["optimize"] = True
        options["save_all"] = True

    elif format == ImageFormat.AVIF:
        options["quality"] = quality if quality is not None else 80

    elif format == ImageFormat.TIFF:
        options["compression"] = "tiff_lzw"

    elif format == ImageFormat.PDF:
        options["resolution"] = 100.0

    elif format == ImageFormat.BMP:
        pass

    elif format == ImageFormat.ICO:
        pass

    elif format in (
        ImageFormat.TGA,
        ImageFormat.PCX,
        ImageFormat.PPM,
        ImageFormat.SGI,
        ImageFormat.XBM,
        ImageFormat.DDS,
    ):
        pass

    else:
        if quality is not None:
            options["quality"] = quality

    return options


__all__ = [
    "MAX_IMAGE_PIXELS",
    "ImageTooLargeError",
    "apply_pillow_limit",
    "assert_within_pixel_budget",
    "normalise_mode",
    "resize",
    "save",
    "save_options",
]
