# Generated by scripts/oss/project_local_engine.py — DO NOT EDIT.
# Regenerate rather than patch; hand edits are rejected by the drift gate.
# SPDX-License-Identifier: Apache-2.0

"""How this package's format names map onto Pillow's.

Pillow's `save()` takes its own format strings, and they are not the file
extensions: JPEG is `"JPEG"` and never `"JPG"`, JPEG 2000 is `"JPEG2000"`. Most
formats need no translation, so the map holds only the ones that do and
everything else falls back to the uppercased extension.

Pure data. Nothing here opens a file or imports Pillow.
"""

from __future__ import annotations

from convilyn.local._engine.formats import ImageFormat

PIL_FORMAT_MAP: dict[ImageFormat, str] = {
    ImageFormat.JPG: "JPEG",
    ImageFormat.JP2: "JPEG2000",
    ImageFormat.TGA: "TGA",
    ImageFormat.ICO: "ICO",
    ImageFormat.SGI: "SGI",
    ImageFormat.XBM: "XBM",
    ImageFormat.PCX: "PCX",
    ImageFormat.PPM: "PPM",
    ImageFormat.DDS: "DDS",
    ImageFormat.PDF: "PDF",
}

RAW_FORMATS = frozenset({ImageFormat.DNG, ImageFormat.CR2, ImageFormat.NEF})


def get_pil_format_name(target: ImageFormat) -> str:
    """The Pillow format string to save a format as."""
    return PIL_FORMAT_MAP.get(target, target.value.upper())


__all__ = ["PIL_FORMAT_MAP", "RAW_FORMATS", "get_pil_format_name"]
