# Generated by scripts/oss/project_convert_formats.py — DO NOT EDIT.
# Regenerate rather than patch; hand edits are rejected by the drift gate.
# SPDX-License-Identifier: Apache-2.0

"""The format vocabulary each free conversion family speaks.

Membership here means a spelling NAMES a format in that family — never that a
particular conversion between two of them is producible. Which pairs run is
published by the backend at ``GET /api/v1/{document,image,media}/support`` and
enforced at job admission; this SDK deliberately carries no copy of it.

``convilyn.local`` has its own, separate vocabulary
(``convilyn.local._engine.formats``): it describes what the OFFLINE engine on
this machine can do, which is a different question with a different answer.
"""

from __future__ import annotations

#: Formats `document_conversion` speaks (backend ``DocumentFormat``).
DOCUMENT_FORMATS: frozenset[str] = frozenset(
    {
        "azw3",
        "csv",
        "doc",
        "docx",
        "epub",
        "html",
        "md",
        "mobi",
        "odp",
        "ods",
        "odt",
        "pdf",
        "ppt",
        "pptx",
        "rtf",
        "txt",
        "xls",
        "xlsx",
        "xml",
    }
)

#: Formats `image_conversion` speaks (backend ``ImageFormat``).
IMAGE_FORMATS: frozenset[str] = frozenset(
    {
        "avif",
        "bmp",
        "cr2",
        "dds",
        "dng",
        "exr",
        "gif",
        "hdr",
        "heic",
        "ico",
        "jp2",
        "jpg",
        "nef",
        "pcd",
        "pcx",
        "pdf",
        "png",
        "ppm",
        "psd",
        "sgi",
        "svg",
        "tga",
        "tiff",
        "webp",
        "xbm",
        "xpm",
    }
)

#: Formats `media_processing` speaks (backend ``MediaFormat``).
MEDIA_FORMATS: frozenset[str] = frozenset(
    {
        "avi",
        "flac",
        "gif",
        "m4a",
        "mkv",
        "mov",
        "mp3",
        "mp4",
        "ogg",
        "wav",
        "webm",
    }
)

#: Alternative spellings of an image format, resolved to the canonical one.
#: Upstream calls this table the single source of truth for image alias
#: resolution, so the SDK resolves through it rather than inventing a second.
IMAGE_FORMAT_ALIASES: dict[str, str] = {
    "bw": "sgi",
    "cur": "ico",
    "dib": "bmp",
    "heif": "heic",
    "j2c": "jp2",
    "j2k": "jp2",
    "jfi": "jpg",
    "jfif": "jpg",
    "jif": "jpg",
    "jpe": "jpg",
    "jpeg": "jpg",
    "jpeg2000": "jp2",
    "jps": "jpg",
    "jpx": "jp2",
    "pbm": "ppm",
    "pgm": "ppm",
    "pnm": "ppm",
    "rgb": "sgi",
    "rgba": "sgi",
    "rgbe": "hdr",
    "targa": "tga",
    "tif": "tiff",
}


__all__ = [
    "DOCUMENT_FORMATS",
    "IMAGE_FORMATS",
    "IMAGE_FORMAT_ALIASES",
    "MEDIA_FORMATS",
]
