# Generated by scripts/oss/project_local_engine.py — DO NOT EDIT.
# Regenerate rather than patch; hand edits are rejected by the drift gate.
# SPDX-License-Identifier: Apache-2.0

"""What a media conversion decides, separated from what it runs.

Running ffmpeg means a process, a path and a file on disk. Everything decided
rather than performed — which codecs a container takes, how a quality preset
becomes arguments, which conversions are possible at all, and whether a finished
process actually produced something — is a pure function of its arguments, and
that is what lives here.

Three things this module deliberately leaves to its caller, each because putting
it here would make a guarantee weaker rather than stronger:

- **It builds no command line, only arguments.** The program's path is resolved
  separately, because where ffmpeg lives is a fact about the machine and not
  about the conversion.
- **It does not add the overwrite flag.** That belongs beside the file being
  overwritten, where a reader can see what is at risk.
- **It does not restrict input protocols.** The caller applies that immediately
  before spawning, so there is exactly one place to look for it. See
  `hardening`.
"""

from __future__ import annotations

from convilyn.local._engine.media.formats import (
    AUDIO_FORMATS,
    FORMAT_METADATA,
    VIDEO_FORMATS,
    MediaFormat,
)

_VIDEO_CODECS: dict[MediaFormat, list[str]] = {
    MediaFormat.MP4: ["-c:v", "libx264", "-c:a", "aac"],
    MediaFormat.WEBM: ["-c:v", "libvpx-vp9", "-c:a", "libopus"],
    MediaFormat.MOV: ["-c:v", "libx264", "-c:a", "aac", "-f", "mov"],
    MediaFormat.AVI: ["-c:v", "libx264", "-c:a", "aac"],
    MediaFormat.MKV: ["-c:v", "libx264", "-c:a", "aac"],
}

_AUDIO_CODECS: dict[MediaFormat, tuple[list[str], bool]] = {
    MediaFormat.MP3: (["-c:a", "libmp3lame"], True),
    MediaFormat.WAV: (["-c:a", "pcm_s16le"], False),
    MediaFormat.OGG: (["-c:a", "libvorbis"], True),
    MediaFormat.M4A: (["-c:a", "aac"], True),
    MediaFormat.FLAC: (["-c:a", "flac"], False),
}

_DEFAULT_AUDIO_BITRATE = "192k"

TRANSCODE_TARGET_FORMATS: frozenset[MediaFormat] = frozenset(_VIDEO_CODECS) | frozenset(
    _AUDIO_CODECS
)


def get_ffmpeg_options(target_format: MediaFormat, quality: str) -> list[str]:
    """The encoder arguments for a quality preset.

    Video targets get a quality factor and the container's codec pair; audio targets
    drop the video stream and get a bitrate, unless the codec is lossless — where a
    bitrate would be meaningless rather than merely ignored.
    """
    options: list[str] = []
    if target_format not in AUDIO_FORMATS:
        options.extend(["-crf", "18" if quality == "high" else "23"])
        options.extend(_VIDEO_CODECS.get(target_format, []))
        return options

    codec, takes_bitrate = _AUDIO_CODECS[target_format]
    options.append("-vn")
    options.extend(codec)
    if takes_bitrate:
        options.extend(["-b:a", _DEFAULT_AUDIO_BITRATE])
    return options


def build_transcode_argv(
    source: str, output: str, target_format: MediaFormat, quality: str
) -> list[str]:
    """Every ffmpeg argument for one conversion, excluding the program itself.

    Returned without the overwrite flag and without an input-protocol restriction;
    the caller adds both. See the module notes for why.
    """
    return ["-i", source, *get_ffmpeg_options(target_format, quality), output]


def adjudicate_transcode(returncode: int, stderr: str, produced_bytes: int) -> str | None:
    """Why a finished conversion failed, or `None` when it produced output.

    **A zero exit status is not evidence of output.** ffmpeg declines to overwrite an
    existing file, says so, and still exits successfully — so a caller that creates
    its output path first and then trusts the exit status will report an empty file
    as a success. The size is the evidence; the exit status only distinguishes two
    kinds of failure.
    """
    if returncode != 0:
        return f"FFmpeg transcoding failed: {stderr}"
    if produced_bytes == 0:
        return (
            "FFmpeg reported success but produced a 0-byte output. "
            f"stderr: {(stderr or '').strip()[-400:]}"
        )
    return None


def transcode_pairs() -> tuple[tuple[MediaFormat, MediaFormat], ...]:
    """Every `(source, target)` pair a conversion can actually produce.

    Four rules, none of them readable off the format list alone:

    1. A format cannot convert to itself.
    2. Audio cannot become video.
    3. A readable container is not automatically a writable one — only formats with
       an encoder can be produced. Animated GIF is the live case: a legitimate
       source, never a target.
    4. A source carrying no audio cannot produce an audio file. Derived from the
       format metadata rather than by naming a format, so a silent container added
       later is covered.

    The order is stable, so anything rendering these does not depend on set
    iteration order.
    """
    return tuple(
        (source, target)
        for source in MediaFormat
        for target in MediaFormat
        if source != target
        and not (source in AUDIO_FORMATS and target in VIDEO_FORMATS)
        and target in TRANSCODE_TARGET_FORMATS
        and not (
            target in AUDIO_FORMATS and not FORMAT_METADATA[source].get("supports_audio", True)
        )
    )


def transcode_category(source: MediaFormat, target: MediaFormat) -> str:
    """Classify a pair by stream kind: video to video, video to audio, or audio to
    audio.

    Total over every ordered pair, including the audio-to-video combination that
    `transcode_pairs` never yields. Classifying and producing are separate
    questions, and an answer that was only correct for the pairs its sibling happens
    to allow would be relying on that overlap holding.
    """
    src_is_video = source in VIDEO_FORMATS
    tgt_is_video = target in VIDEO_FORMATS
    if src_is_video and tgt_is_video:
        return "video-to-video"
    if src_is_video:
        return "video-to-audio"
    if tgt_is_video:
        return "audio-to-video"
    return "audio-to-audio"
