# Generated by scripts/oss/project_local_engine.py — DO NOT EDIT.
# Regenerate rather than patch; hand edits are rejected by the drift gate.
# SPDX-License-Identifier: Apache-2.0

"""The media containers this engine knows, and what each one carries.

`FORMAT_METADATA` is the per-format record; `VIDEO_FORMATS` and `AUDIO_FORMATS`
are derived from its `category` field rather than listed separately, so the two
cannot disagree about where a format belongs.

`supports_audio` is the field that does real work. A container carrying no audio
stream cannot be the source of an audio file, and reading that fact off the
metadata means a silent format added later is handled without anyone editing a
rule.

Pure data. Nothing here opens a file or runs a program.
"""

from enum import Enum
from typing import Any


class MediaFormat(str, Enum):
    """A media container, spelled as its file extension.

    Membership means this engine can *read* the format. It does not mean the format
    can be written: several containers are readable sources with no encoder, and
    `convert_core.TRANSCODE_TARGET_FORMATS` is the set that can be produced.
    """

    MP4 = "mp4"
    WEBM = "webm"
    AVI = "avi"
    MOV = "mov"
    MKV = "mkv"
    GIF = "gif"

    MP3 = "mp3"
    WAV = "wav"
    OGG = "ogg"
    M4A = "m4a"
    FLAC = "flac"


FORMAT_METADATA: dict[MediaFormat, dict[str, Any]] = {
    MediaFormat.MP4: {
        "display_name": "MP4",
        "description": "MPEG-4 Part 14",
        "category": "video",
        "typical_use": "Universal video format",
        "supports_video": True,
        "supports_audio": True,
    },
    MediaFormat.WEBM: {
        "display_name": "WebM",
        "description": "Web Media",
        "category": "video",
        "typical_use": "Web video streaming",
        "supports_video": True,
        "supports_audio": True,
    },
    MediaFormat.AVI: {
        "display_name": "AVI",
        "description": "Audio Video Interleave",
        "category": "video",
        "typical_use": "Legacy video format",
        "supports_video": True,
        "supports_audio": True,
    },
    MediaFormat.MOV: {
        "display_name": "MOV",
        "description": "QuickTime Movie",
        "category": "video",
        "typical_use": "Apple video format",
        "supports_video": True,
        "supports_audio": True,
    },
    MediaFormat.MKV: {
        "display_name": "MKV",
        "description": "Matroska Video",
        "category": "video",
        "typical_use": "High-quality video container",
        "supports_video": True,
        "supports_audio": True,
    },
    MediaFormat.GIF: {
        "display_name": "GIF",
        "description": "Graphics Interchange Format",
        "category": "video",
        "typical_use": "Animated images",
        "supports_video": True,
        "supports_audio": False,
    },
    MediaFormat.MP3: {
        "display_name": "MP3",
        "description": "MPEG Audio Layer 3",
        "category": "audio",
        "typical_use": "Universal audio format",
        "supports_video": False,
        "supports_audio": True,
    },
    MediaFormat.WAV: {
        "display_name": "WAV",
        "description": "Waveform Audio File",
        "category": "audio",
        "typical_use": "Uncompressed audio",
        "supports_video": False,
        "supports_audio": True,
    },
    MediaFormat.OGG: {
        "display_name": "OGG",
        "description": "Ogg Vorbis",
        "category": "audio",
        "typical_use": "Open-source audio",
        "supports_video": False,
        "supports_audio": True,
    },
    MediaFormat.M4A: {
        "display_name": "M4A",
        "description": "MPEG-4 Audio",
        "category": "audio",
        "typical_use": "Apple audio format",
        "supports_video": False,
        "supports_audio": True,
    },
    MediaFormat.FLAC: {
        "display_name": "FLAC",
        "description": "Free Lossless Audio Codec",
        "category": "audio",
        "typical_use": "Lossless audio compression",
        "supports_video": False,
        "supports_audio": True,
    },
}

VIDEO_FORMATS: frozenset[MediaFormat] = frozenset(
    fmt for fmt, meta in FORMAT_METADATA.items() if meta["category"] == "video"
)

AUDIO_FORMATS: frozenset[MediaFormat] = frozenset(
    fmt for fmt, meta in FORMAT_METADATA.items() if meta["category"] == "audio"
)
