# Generated by scripts/oss/project_local_engine.py — DO NOT EDIT.
# Regenerate rather than patch; hand edits are rejected by the drift gate.
# SPDX-License-Identifier: Apache-2.0

"""Restricting what a media conversion is allowed to open.

**Why this exists.** ffmpeg's default protocol set includes `http`, `https` and
`tcp`, and several demuxers open inputs *named inside the media file itself* —
an HLS or DASH manifest, a `concat` list, a QuickTime reference box. So a
crafted file can make the conversion issue outbound network requests from the
machine running it. Restricting inputs to the local filesystem closes that,
and costs nothing: every input this engine converts is a file you chose.

**What it does not cover**, stated so the box is not ticked falsely:

- Filter sources open their own contexts, so `subtitles=`, `movie=` and
  metadata-from-file references are outside an input-scoped restriction. What
  contains those is the path argument itself.
- Outputs are unconstrained. Every output path here is one the caller chose, so
  constraining them would add risk without adding safety.
- A reference box naming a *local* file still reads that file. The restriction
  blocks the network form, which is the reachable half.
"""

from __future__ import annotations

from collections.abc import Sequence

INPUT_PROTOCOL_WHITELIST = "file"

_FLAG = "-protocol_whitelist"

PROTOCOL_WHITELIST_ARGS: tuple[str, ...] = (_FLAG, INPUT_PROTOCOL_WHITELIST)


def harden_ffmpeg_args(args: Sequence[str]) -> list[str]:
    """Restrict every input in an ffmpeg argument list to the local filesystem.

    The option is per-input, so it must precede each input rather than appear once,
    and it propagates to any further input that input opens — which is what closes
    the manifest and playlist cases.

    Idempotent, and never mutates the list it is given.
    """
    hardened: list[str] = []
    for token in args:
        if token == "-i" and not _already_hardened(hardened):
            hardened.append(_FLAG)
            hardened.append(INPUT_PROTOCOL_WHITELIST)
        hardened.append(str(token))
    return hardened


def harden_ffprobe_args(args: Sequence[str]) -> list[str]:
    """The same restriction for a probe, whose input is positional.

    Prepending covers both the positional and the flagged form. Idempotent, and a
    no-op on an empty list.
    """
    if not args:
        return []
    if _FLAG in args:
        return [str(a) for a in args]
    return [_FLAG, INPUT_PROTOCOL_WHITELIST, *(str(a) for a in args)]


def _already_hardened(emitted: list[str]) -> bool:
    return len(emitted) >= 2 and emitted[-2] == _FLAG


__all__ = [
    "INPUT_PROTOCOL_WHITELIST",
    "PROTOCOL_WHITELIST_ARGS",
    "harden_ffmpeg_args",
    "harden_ffprobe_args",
]
